// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.0
// source: bonus.proto

package cli

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnlineBonusInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOpen                  bool   `protobuf:"varint,1,opt,name=IsOpen,proto3" json:"IsOpen,omitempty"`                                    // Bonus是否开放
	LatestRefreshTime       int64  `protobuf:"varint,2,opt,name=LatestRefreshTime,proto3" json:"LatestRefreshTime,omitempty"`              // 最后刷新时间(s)
	LifeEndTime             int64  `protobuf:"varint,3,opt,name=LifeEndTime,proto3" json:"LifeEndTime,omitempty"`                          // 生存时间截止时间点(s), -1为永久生效
	BonusLevel              int64  `protobuf:"varint,4,opt,name=BonusLevel,proto3" json:"BonusLevel,omitempty"`                            // Bonus等级
	ProductID               string `protobuf:"bytes,5,opt,name=ProductID,proto3" json:"ProductID,omitempty"`                               // 获得Bonus奖励需要支付的商品ID
	BonusCoin               int64  `protobuf:"varint,6,opt,name=BonusCoin,proto3" json:"BonusCoin,omitempty"`                              // Bonus奖励金币数
	TargetBetValue          int64  `protobuf:"varint,7,opt,name=TargetBetValue,proto3" json:"TargetBetValue,omitempty"`                    // 目标下注金额
	Progress                int64  `protobuf:"varint,8,opt,name=Progress,proto3" json:"Progress,omitempty"`                                // 已经完成的下注金额
	Finished                bool   `protobuf:"varint,9,opt,name=Finished,proto3" json:"Finished,omitempty"`                                // 目标下注金额是否已完成
	Recharged               bool   `protobuf:"varint,10,opt,name=Recharged,proto3" json:"Recharged,omitempty"`                             // 是否已支付
	Accquired               bool   `protobuf:"varint,11,opt,name=Accquired,proto3" json:"Accquired,omitempty"`                             // 是否已领取
	EndTimeForCollectAdder  int64  `protobuf:"varint,12,opt,name=EndTimeForCollectAdder,proto3" json:"EndTimeForCollectAdder,omitempty"`   // 集满加赠截止时间点(s)
	CollectAdderCount       int64  `protobuf:"varint,13,opt,name=CollectAdderCount,proto3" json:"CollectAdderCount,omitempty"`             // 集满加赠金币数
	EndTimeForRechargeAdder int64  `protobuf:"varint,14,opt,name=EndTimeForRechargeAdder,proto3" json:"EndTimeForRechargeAdder,omitempty"` // 支付加赠截止时间点(s)
	RechargeAdderCount      int64  `protobuf:"varint,15,opt,name=RechargeAdderCount,proto3" json:"RechargeAdderCount,omitempty"`           // 支付加赠金币数
	CollectedTime           int64  `protobuf:"varint,16,opt,name=CollectedTime,proto3" json:"CollectedTime,omitempty"`                     // 集满时间点(s)
	RechargedTime           int64  `protobuf:"varint,17,opt,name=RechargedTime,proto3" json:"RechargedTime,omitempty"`                     // 支付时间点(s)
}

func (x *OnlineBonusInfo) Reset() {
	*x = OnlineBonusInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bonus_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineBonusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBonusInfo) ProtoMessage() {}

func (x *OnlineBonusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bonus_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBonusInfo.ProtoReflect.Descriptor instead.
func (*OnlineBonusInfo) Descriptor() ([]byte, []int) {
	return file_bonus_proto_rawDescGZIP(), []int{0}
}

func (x *OnlineBonusInfo) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *OnlineBonusInfo) GetLatestRefreshTime() int64 {
	if x != nil {
		return x.LatestRefreshTime
	}
	return 0
}

func (x *OnlineBonusInfo) GetLifeEndTime() int64 {
	if x != nil {
		return x.LifeEndTime
	}
	return 0
}

func (x *OnlineBonusInfo) GetBonusLevel() int64 {
	if x != nil {
		return x.BonusLevel
	}
	return 0
}

func (x *OnlineBonusInfo) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *OnlineBonusInfo) GetBonusCoin() int64 {
	if x != nil {
		return x.BonusCoin
	}
	return 0
}

func (x *OnlineBonusInfo) GetTargetBetValue() int64 {
	if x != nil {
		return x.TargetBetValue
	}
	return 0
}

func (x *OnlineBonusInfo) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *OnlineBonusInfo) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *OnlineBonusInfo) GetRecharged() bool {
	if x != nil {
		return x.Recharged
	}
	return false
}

func (x *OnlineBonusInfo) GetAccquired() bool {
	if x != nil {
		return x.Accquired
	}
	return false
}

func (x *OnlineBonusInfo) GetEndTimeForCollectAdder() int64 {
	if x != nil {
		return x.EndTimeForCollectAdder
	}
	return 0
}

func (x *OnlineBonusInfo) GetCollectAdderCount() int64 {
	if x != nil {
		return x.CollectAdderCount
	}
	return 0
}

func (x *OnlineBonusInfo) GetEndTimeForRechargeAdder() int64 {
	if x != nil {
		return x.EndTimeForRechargeAdder
	}
	return 0
}

func (x *OnlineBonusInfo) GetRechargeAdderCount() int64 {
	if x != nil {
		return x.RechargeAdderCount
	}
	return 0
}

func (x *OnlineBonusInfo) GetCollectedTime() int64 {
	if x != nil {
		return x.CollectedTime
	}
	return 0
}

func (x *OnlineBonusInfo) GetRechargedTime() int64 {
	if x != nil {
		return x.RechargedTime
	}
	return 0
}

// OnlineBonusInfoRequest 查询集钱罐信息请求 1131
type OnlineBonusInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnlineBonusInfoRequest) Reset() {
	*x = OnlineBonusInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bonus_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineBonusInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBonusInfoRequest) ProtoMessage() {}

func (x *OnlineBonusInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bonus_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBonusInfoRequest.ProtoReflect.Descriptor instead.
func (*OnlineBonusInfoRequest) Descriptor() ([]byte, []int) {
	return file_bonus_proto_rawDescGZIP(), []int{1}
}

// OnlineBonusInfoResponse 查询集钱罐信息响应 1141
type OnlineBonusInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  int64            `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Bonus *OnlineBonusInfo `protobuf:"bytes,2,opt,name=Bonus,proto3" json:"Bonus,omitempty"` // 集钱罐信息
}

func (x *OnlineBonusInfoResponse) Reset() {
	*x = OnlineBonusInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bonus_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineBonusInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBonusInfoResponse) ProtoMessage() {}

func (x *OnlineBonusInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bonus_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBonusInfoResponse.ProtoReflect.Descriptor instead.
func (*OnlineBonusInfoResponse) Descriptor() ([]byte, []int) {
	return file_bonus_proto_rawDescGZIP(), []int{2}
}

func (x *OnlineBonusInfoResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineBonusInfoResponse) GetBonus() *OnlineBonusInfo {
	if x != nil {
		return x.Bonus
	}
	return nil
}

// OnlineBonusOpenPush 打开集钱罐推送 1142
type OnlineBonusOpenPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64            `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Coin    int64            `protobuf:"varint,2,opt,name=Coin,proto3" json:"Coin,omitempty"`       // 领取集钱罐获得的金币数
	EndCoin int64            `protobuf:"varint,3,opt,name=EndCoin,proto3" json:"EndCoin,omitempty"` // 玩家最终的金币数
	Bonus   *OnlineBonusInfo `protobuf:"bytes,4,opt,name=Bonus,proto3" json:"Bonus,omitempty"`      // 最新集钱罐信息
}

func (x *OnlineBonusOpenPush) Reset() {
	*x = OnlineBonusOpenPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bonus_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineBonusOpenPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBonusOpenPush) ProtoMessage() {}

func (x *OnlineBonusOpenPush) ProtoReflect() protoreflect.Message {
	mi := &file_bonus_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBonusOpenPush.ProtoReflect.Descriptor instead.
func (*OnlineBonusOpenPush) Descriptor() ([]byte, []int) {
	return file_bonus_proto_rawDescGZIP(), []int{3}
}

func (x *OnlineBonusOpenPush) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineBonusOpenPush) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *OnlineBonusOpenPush) GetEndCoin() int64 {
	if x != nil {
		return x.EndCoin
	}
	return 0
}

func (x *OnlineBonusOpenPush) GetBonus() *OnlineBonusInfo {
	if x != nil {
		return x.Bonus
	}
	return nil
}

// OnlineBonusProgressPush 集钱罐收集进度变化 1143
type OnlineBonusProgressPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActiveProgress int64 `protobuf:"varint,1,opt,name=ActiveProgress,proto3" json:"ActiveProgress,omitempty"` // 集钱罐当前进度(0-100)
}

func (x *OnlineBonusProgressPush) Reset() {
	*x = OnlineBonusProgressPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bonus_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineBonusProgressPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBonusProgressPush) ProtoMessage() {}

func (x *OnlineBonusProgressPush) ProtoReflect() protoreflect.Message {
	mi := &file_bonus_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBonusProgressPush.ProtoReflect.Descriptor instead.
func (*OnlineBonusProgressPush) Descriptor() ([]byte, []int) {
	return file_bonus_proto_rawDescGZIP(), []int{4}
}

func (x *OnlineBonusProgressPush) GetActiveProgress() int64 {
	if x != nil {
		return x.ActiveProgress
	}
	return 0
}

// OnlineBonusFinishPush 集钱罐收集完成 1144
type OnlineBonusFinishPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bonus *OnlineBonusInfo `protobuf:"bytes,1,opt,name=Bonus,proto3" json:"Bonus,omitempty"` // 集满的集钱罐信息
}

func (x *OnlineBonusFinishPush) Reset() {
	*x = OnlineBonusFinishPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bonus_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineBonusFinishPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBonusFinishPush) ProtoMessage() {}

func (x *OnlineBonusFinishPush) ProtoReflect() protoreflect.Message {
	mi := &file_bonus_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBonusFinishPush.ProtoReflect.Descriptor instead.
func (*OnlineBonusFinishPush) Descriptor() ([]byte, []int) {
	return file_bonus_proto_rawDescGZIP(), []int{5}
}

func (x *OnlineBonusFinishPush) GetBonus() *OnlineBonusInfo {
	if x != nil {
		return x.Bonus
	}
	return nil
}

var File_bonus_proto protoreflect.FileDescriptor

var file_bonus_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x6f, 0x6e, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63,
	0x6c, 0x69, 0x22, 0x8d, 0x05, 0x0a, 0x0f, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x6f, 0x6e,
	0x75, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x4f, 0x70, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x49, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x2c,
	0x0a, 0x11, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x4c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x4c, 0x69, 0x66, 0x65, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x4c, 0x69, 0x66, 0x65, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1c,
	0x0a, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09,
	0x42, 0x6f, 0x6e, 0x75, 0x73, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x42, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65,
	0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x52,
	0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x41, 0x63, 0x63,
	0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x36, 0x0a, 0x16, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x46, 0x6f, 0x72, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x64, 0x64, 0x65, 0x72,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x16, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x46,
	0x6f, 0x72, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x64, 0x64, 0x65, 0x72, 0x12, 0x2c,
	0x0a, 0x11, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x64, 0x64, 0x65, 0x72, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x41, 0x64, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x17,
	0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x41, 0x64, 0x64, 0x65, 0x72, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x17, 0x45,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x46, 0x6f, 0x72, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67,
	0x65, 0x41, 0x64, 0x64, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x41, 0x64, 0x64, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0f, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x12, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x41, 0x64, 0x64, 0x65,
	0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0d,
	0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x11, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x18, 0x0a, 0x16, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x6f, 0x6e, 0x75,
	0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x17,
	0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x42,
	0x6f, 0x6e, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x69,
	0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x13, 0x4f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x75, 0x73, 0x68, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x43, 0x6f,
	0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x45, 0x6e, 0x64, 0x43, 0x6f, 0x69,
	0x6e, 0x12, 0x2a, 0x0a, 0x05, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x6f, 0x6e,
	0x75, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x22, 0x41, 0x0a,
	0x17, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x65, 0x73, 0x73, 0x50, 0x75, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0e, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x43, 0x0a, 0x15, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x50, 0x75, 0x73, 0x68, 0x12, 0x2a, 0x0a, 0x05, 0x42, 0x6f, 0x6e,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x42, 0x6f, 0x6e, 0x75, 0x73, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bonus_proto_rawDescOnce sync.Once
	file_bonus_proto_rawDescData = file_bonus_proto_rawDesc
)

func file_bonus_proto_rawDescGZIP() []byte {
	file_bonus_proto_rawDescOnce.Do(func() {
		file_bonus_proto_rawDescData = protoimpl.X.CompressGZIP(file_bonus_proto_rawDescData)
	})
	return file_bonus_proto_rawDescData
}

var file_bonus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bonus_proto_goTypes = []interface{}{
	(*OnlineBonusInfo)(nil),         // 0: cli.OnlineBonusInfo
	(*OnlineBonusInfoRequest)(nil),  // 1: cli.OnlineBonusInfoRequest
	(*OnlineBonusInfoResponse)(nil), // 2: cli.OnlineBonusInfoResponse
	(*OnlineBonusOpenPush)(nil),     // 3: cli.OnlineBonusOpenPush
	(*OnlineBonusProgressPush)(nil), // 4: cli.OnlineBonusProgressPush
	(*OnlineBonusFinishPush)(nil),   // 5: cli.OnlineBonusFinishPush
}
var file_bonus_proto_depIdxs = []int32{
	0, // 0: cli.OnlineBonusInfoResponse.Bonus:type_name -> cli.OnlineBonusInfo
	0, // 1: cli.OnlineBonusOpenPush.Bonus:type_name -> cli.OnlineBonusInfo
	0, // 2: cli.OnlineBonusFinishPush.Bonus:type_name -> cli.OnlineBonusInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bonus_proto_init() }
func file_bonus_proto_init() {
	if File_bonus_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bonus_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineBonusInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bonus_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineBonusInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bonus_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineBonusInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bonus_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineBonusOpenPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bonus_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineBonusProgressPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bonus_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineBonusFinishPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bonus_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bonus_proto_goTypes,
		DependencyIndexes: file_bonus_proto_depIdxs,
		MessageInfos:      file_bonus_proto_msgTypes,
	}.Build()
	File_bonus_proto = out.File
	file_bonus_proto_rawDesc = nil
	file_bonus_proto_goTypes = nil
	file_bonus_proto_depIdxs = nil
}
