// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.0
// source: hall.proto

package cli

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID     int64  `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`
	Token   string `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	Package string `protobuf:"bytes,3,opt,name=Package,proto3" json:"Package,omitempty"`
	Type    string `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Account string `protobuf:"bytes,5,opt,name=Account,proto3" json:"Account,omitempty"`
	Device  string `protobuf:"bytes,6,opt,name=Device,proto3" json:"Device,omitempty"`
	Cli     *Cli   `protobuf:"bytes,7,opt,name=Cli,proto3" json:"Cli,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *LoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginRequest) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *LoginRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LoginRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *LoginRequest) GetCli() *Cli {
	if x != nil {
		return x.Cli
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code                 int64                 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	UID                  int64                 `protobuf:"varint,2,opt,name=UID,proto3" json:"UID,omitempty"`
	Coin                 int64                 `protobuf:"varint,3,opt,name=Coin,proto3" json:"Coin,omitempty"`
	Srv                  *Srv                  `protobuf:"bytes,4,opt,name=Srv,proto3" json:"Srv,omitempty"`
	Proc                 *Proc                 `protobuf:"bytes,5,opt,name=Proc,proto3" json:"Proc,omitempty"`
	Acc                  *Acc                  `protobuf:"bytes,6,opt,name=Acc,proto3" json:"Acc,omitempty"`
	User                 *User                 `protobuf:"bytes,7,opt,name=User,proto3" json:"User,omitempty"`
	Char                 *Char                 `protobuf:"bytes,8,opt,name=Char,proto3" json:"Char,omitempty"`
	Book                 *Book                 `protobuf:"bytes,9,opt,name=Book,proto3" json:"Book,omitempty"`
	Config               *HallConfig           `protobuf:"bytes,10,opt,name=Config,proto3" json:"Config,omitempty"`
	SpecialOfferCharged  bool                  `protobuf:"varint,11,opt,name=SpecialOfferCharged,proto3" json:"SpecialOfferCharged,omitempty"`  //是否已经完成首充
	AggIncRechargeCoin   int64                 `protobuf:"varint,12,opt,name=AggIncRechargeCoin,proto3" json:"AggIncRechargeCoin,omitempty"`    //累计充值
	SigninAwardData      *SigninAwardData      `protobuf:"bytes,13,opt,name=SigninAwardData,proto3" json:"SigninAwardData,omitempty"`           //签到奖励状态
	MailList             []*MailItem           `protobuf:"bytes,14,rep,name=MailList,proto3" json:"MailList,omitempty"`                         //邮件列表
	Inviter              int64                 `protobuf:"varint,15,opt,name=Inviter,proto3" json:"Inviter,omitempty"`                          //邀请者
	CustomerList         []*CustomerItem       `protobuf:"bytes,16,rep,name=CustomerList,proto3" json:"CustomerList,omitempty"`                 //客服列表
	PropList             []*Prop               `protobuf:"bytes,17,rep,name=PropList,proto3" json:"PropList,omitempty"`                         // 道具列表
	AddUpSigninAwardData *AddUpSigninAwardData `protobuf:"bytes,18,opt,name=AddUpSigninAwardData,proto3" json:"AddUpSigninAwardData,omitempty"` //累计签到奖励状态
	ShopAdderData        *ShopAdderData        `protobuf:"bytes,19,opt,name=ShopAdderData,proto3" json:"ShopAdderData,omitempty"`               // 商城特惠商品状态
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResponse) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *LoginResponse) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *LoginResponse) GetSrv() *Srv {
	if x != nil {
		return x.Srv
	}
	return nil
}

func (x *LoginResponse) GetProc() *Proc {
	if x != nil {
		return x.Proc
	}
	return nil
}

func (x *LoginResponse) GetAcc() *Acc {
	if x != nil {
		return x.Acc
	}
	return nil
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponse) GetChar() *Char {
	if x != nil {
		return x.Char
	}
	return nil
}

func (x *LoginResponse) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *LoginResponse) GetConfig() *HallConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *LoginResponse) GetSpecialOfferCharged() bool {
	if x != nil {
		return x.SpecialOfferCharged
	}
	return false
}

func (x *LoginResponse) GetAggIncRechargeCoin() int64 {
	if x != nil {
		return x.AggIncRechargeCoin
	}
	return 0
}

func (x *LoginResponse) GetSigninAwardData() *SigninAwardData {
	if x != nil {
		return x.SigninAwardData
	}
	return nil
}

func (x *LoginResponse) GetMailList() []*MailItem {
	if x != nil {
		return x.MailList
	}
	return nil
}

func (x *LoginResponse) GetInviter() int64 {
	if x != nil {
		return x.Inviter
	}
	return 0
}

func (x *LoginResponse) GetCustomerList() []*CustomerItem {
	if x != nil {
		return x.CustomerList
	}
	return nil
}

func (x *LoginResponse) GetPropList() []*Prop {
	if x != nil {
		return x.PropList
	}
	return nil
}

func (x *LoginResponse) GetAddUpSigninAwardData() *AddUpSigninAwardData {
	if x != nil {
		return x.AddUpSigninAwardData
	}
	return nil
}

func (x *LoginResponse) GetShopAdderData() *ShopAdderData {
	if x != nil {
		return x.ShopAdderData
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{2}
}

type LogoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 玩家冲突
type LoginConflictRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginConflictRequest) Reset() {
	*x = LoginConflictRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginConflictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginConflictRequest) ProtoMessage() {}

func (x *LoginConflictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginConflictRequest.ProtoReflect.Descriptor instead.
func (*LoginConflictRequest) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{4}
}

type LoginConflictPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service string `protobuf:"bytes,1,opt,name=Service,proto3" json:"Service,omitempty"`
}

func (x *LoginConflictPush) Reset() {
	*x = LoginConflictPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginConflictPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginConflictPush) ProtoMessage() {}

func (x *LoginConflictPush) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginConflictPush.ProtoReflect.Descriptor instead.
func (*LoginConflictPush) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{5}
}

func (x *LoginConflictPush) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

// 玩家绑定
type LoginBindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LoginBindRequest) Reset() {
	*x = LoginBindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginBindRequest) ProtoMessage() {}

func (x *LoginBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginBindRequest.ProtoReflect.Descriptor instead.
func (*LoginBindRequest) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{6}
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{7}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{8}
}

// 踢出离线玩家
type KickOfflineReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KickOfflineReq) Reset() {
	*x = KickOfflineReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickOfflineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickOfflineReq) ProtoMessage() {}

func (x *KickOfflineReq) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickOfflineReq.ProtoReflect.Descriptor instead.
func (*KickOfflineReq) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{9}
}

// 封禁玩家请求
type ForbidPlayerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForbidPlayerReq) Reset() {
	*x = ForbidPlayerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForbidPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForbidPlayerReq) ProtoMessage() {}

func (x *ForbidPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForbidPlayerReq.ProtoReflect.Descriptor instead.
func (*ForbidPlayerReq) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{10}
}

// 封禁玩家推送
type ForbidPlayerPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ForbidPlayerPush) Reset() {
	*x = ForbidPlayerPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForbidPlayerPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForbidPlayerPush) ProtoMessage() {}

func (x *ForbidPlayerPush) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForbidPlayerPush.ProtoReflect.Descriptor instead.
func (*ForbidPlayerPush) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{11}
}

type AccountKickPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *AccountKickPush) Reset() {
	*x = AccountKickPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountKickPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountKickPush) ProtoMessage() {}

func (x *AccountKickPush) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountKickPush.ProtoReflect.Descriptor instead.
func (*AccountKickPush) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{12}
}

func (x *AccountKickPush) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type AccountRejectPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *AccountRejectPush) Reset() {
	*x = AccountRejectPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountRejectPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRejectPush) ProtoMessage() {}

func (x *AccountRejectPush) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRejectPush.ProtoReflect.Descriptor instead.
func (*AccountRejectPush) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{13}
}

func (x *AccountRejectPush) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type NotifyReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID   int64  `protobuf:"varint,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`    // 玩家ID
	NotifyType string `protobuf:"bytes,2,opt,name=NotifyType,proto3" json:"NotifyType,omitempty"` // 通知类型
	NotifyData string `protobuf:"bytes,3,opt,name=NotifyData,proto3" json:"NotifyData,omitempty"` // 通知数据
}

func (x *NotifyReq) Reset() {
	*x = NotifyReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyReq) ProtoMessage() {}

func (x *NotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyReq.ProtoReflect.Descriptor instead.
func (*NotifyReq) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{14}
}

func (x *NotifyReq) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *NotifyReq) GetNotifyType() string {
	if x != nil {
		return x.NotifyType
	}
	return ""
}

func (x *NotifyReq) GetNotifyData() string {
	if x != nil {
		return x.NotifyData
	}
	return ""
}

type ActionFailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionID   int64  `protobuf:"varint,1,opt,name=ActionID,proto3" json:"ActionID,omitempty"`    // 请求ID
	FaileType  int64  `protobuf:"varint,2,opt,name=FaileType,proto3" json:"FaileType,omitempty"`  // 失败类型
	NotifyData string `protobuf:"bytes,3,opt,name=NotifyData,proto3" json:"NotifyData,omitempty"` // 失败信息
}

func (x *ActionFailed) Reset() {
	*x = ActionFailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hall_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionFailed) ProtoMessage() {}

func (x *ActionFailed) ProtoReflect() protoreflect.Message {
	mi := &file_hall_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionFailed.ProtoReflect.Descriptor instead.
func (*ActionFailed) Descriptor() ([]byte, []int) {
	return file_hall_proto_rawDescGZIP(), []int{15}
}

func (x *ActionFailed) GetActionID() int64 {
	if x != nil {
		return x.ActionID
	}
	return 0
}

func (x *ActionFailed) GetFaileType() int64 {
	if x != nil {
		return x.FaileType
	}
	return 0
}

func (x *ActionFailed) GetNotifyData() string {
	if x != nil {
		return x.NotifyData
	}
	return ""
}

var File_hall_proto protoreflect.FileDescriptor

var file_hall_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x68, 0x61, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x6c,
	0x69, 0x1a, 0x0d, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb2, 0x01, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x55, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x03, 0x43, 0x6c, 0x69,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x43, 0x6c, 0x69,
	0x52, 0x03, 0x43, 0x6c, 0x69, 0x22, 0xf4, 0x05, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x69,
	0x6e, 0x12, 0x1a, 0x0a, 0x03, 0x53, 0x72, 0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x53, 0x72, 0x76, 0x52, 0x03, 0x53, 0x72, 0x76, 0x12, 0x1d, 0x0a,
	0x04, 0x50, 0x72, 0x6f, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x6c,
	0x69, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x52, 0x04, 0x50, 0x72, 0x6f, 0x63, 0x12, 0x1a, 0x0a, 0x03,
	0x41, 0x63, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x6c, 0x69, 0x2e,
	0x41, 0x63, 0x63, 0x52, 0x03, 0x41, 0x63, 0x63, 0x12, 0x1d, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x43, 0x68, 0x61, 0x72,
	0x52, 0x04, 0x43, 0x68, 0x61, 0x72, 0x12, 0x1d, 0x0a, 0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x52,
	0x04, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x27, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x48, 0x61, 0x6c, 0x6c,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x30,
	0x0a, 0x13, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x43, 0x68,
	0x61, 0x72, 0x67, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x13, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x61, 0x6c, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x64,
	0x12, 0x2e, 0x0a, 0x12, 0x41, 0x67, 0x67, 0x49, 0x6e, 0x63, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x41, 0x67,
	0x67, 0x49, 0x6e, 0x63, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x43, 0x6f, 0x69, 0x6e,
	0x12, 0x3e, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x41, 0x77, 0x61, 0x72, 0x64, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x69, 0x2e,
	0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x41, 0x77, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x0f, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x41, 0x77, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x29, 0x0a, 0x08, 0x4d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0e, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x08, 0x4d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x49,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x49, 0x6e,
	0x76, 0x69, 0x74, 0x65, 0x72, 0x12, 0x35, 0x0a, 0x0c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x10, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6c,
	0x69, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0c,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x08,
	0x50, 0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x11, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x4d, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x55, 0x70, 0x53, 0x69, 0x67, 0x6e,
	0x69, 0x6e, 0x41, 0x77, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x18, 0x12, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x70, 0x53, 0x69, 0x67,
	0x6e, 0x69, 0x6e, 0x41, 0x77, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x14, 0x41, 0x64,
	0x64, 0x55, 0x70, 0x53, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x41, 0x77, 0x61, 0x72, 0x64, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x38, 0x0a, 0x0d, 0x53, 0x68, 0x6f, 0x70, 0x41, 0x64, 0x64, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6c, 0x69, 0x2e,
	0x53, 0x68, 0x6f, 0x70, 0x41, 0x64, 0x64, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0d, 0x53,
	0x68, 0x6f, 0x70, 0x41, 0x64, 0x64, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x0f, 0x0a, 0x0d,
	0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3e, 0x0a,
	0x0e, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x16, 0x0a,
	0x14, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2d, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x43, 0x6f,
	0x6e, 0x66, 0x6c, 0x69, 0x63, 0x74, 0x50, 0x75, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x69, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11,
	0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x10, 0x0a, 0x0e, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x22, 0x11, 0x0a, 0x0f, 0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x22, 0x12, 0x0a, 0x10, 0x46, 0x6f, 0x72, 0x62, 0x69, 0x64,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x22, 0x25, 0x0a, 0x0f, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4b, 0x69, 0x63, 0x6b, 0x50, 0x75, 0x73, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0x27, 0x0a, 0x11, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x6a, 0x65,
	0x63, 0x74, 0x50, 0x75, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x67, 0x0a, 0x09, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x68, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12,
	0x1c, 0x0a, 0x09, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x44, 0x61, 0x74, 0x61, 0x42, 0x08, 0x5a,
	0x06, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hall_proto_rawDescOnce sync.Once
	file_hall_proto_rawDescData = file_hall_proto_rawDesc
)

func file_hall_proto_rawDescGZIP() []byte {
	file_hall_proto_rawDescOnce.Do(func() {
		file_hall_proto_rawDescData = protoimpl.X.CompressGZIP(file_hall_proto_rawDescData)
	})
	return file_hall_proto_rawDescData
}

var file_hall_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_hall_proto_goTypes = []interface{}{
	(*LoginRequest)(nil),         // 0: cli.LoginRequest
	(*LoginResponse)(nil),        // 1: cli.LoginResponse
	(*LogoutRequest)(nil),        // 2: cli.LogoutRequest
	(*LogoutResponse)(nil),       // 3: cli.LogoutResponse
	(*LoginConflictRequest)(nil), // 4: cli.LoginConflictRequest
	(*LoginConflictPush)(nil),    // 5: cli.LoginConflictPush
	(*LoginBindRequest)(nil),     // 6: cli.LoginBindRequest
	(*HeartbeatRequest)(nil),     // 7: cli.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 8: cli.HeartbeatResponse
	(*KickOfflineReq)(nil),       // 9: cli.KickOfflineReq
	(*ForbidPlayerReq)(nil),      // 10: cli.ForbidPlayerReq
	(*ForbidPlayerPush)(nil),     // 11: cli.ForbidPlayerPush
	(*AccountKickPush)(nil),      // 12: cli.AccountKickPush
	(*AccountRejectPush)(nil),    // 13: cli.AccountRejectPush
	(*NotifyReq)(nil),            // 14: cli.NotifyReq
	(*ActionFailed)(nil),         // 15: cli.ActionFailed
	(*Cli)(nil),                  // 16: cli.Cli
	(*Srv)(nil),                  // 17: cli.Srv
	(*Proc)(nil),                 // 18: cli.Proc
	(*Acc)(nil),                  // 19: cli.Acc
	(*User)(nil),                 // 20: cli.User
	(*Char)(nil),                 // 21: cli.Char
	(*Book)(nil),                 // 22: cli.Book
	(*HallConfig)(nil),           // 23: cli.HallConfig
	(*SigninAwardData)(nil),      // 24: cli.SigninAwardData
	(*MailItem)(nil),             // 25: cli.MailItem
	(*CustomerItem)(nil),         // 26: cli.CustomerItem
	(*Prop)(nil),                 // 27: cli.Prop
	(*AddUpSigninAwardData)(nil), // 28: cli.AddUpSigninAwardData
	(*ShopAdderData)(nil),        // 29: cli.ShopAdderData
}
var file_hall_proto_depIdxs = []int32{
	16, // 0: cli.LoginRequest.Cli:type_name -> cli.Cli
	17, // 1: cli.LoginResponse.Srv:type_name -> cli.Srv
	18, // 2: cli.LoginResponse.Proc:type_name -> cli.Proc
	19, // 3: cli.LoginResponse.Acc:type_name -> cli.Acc
	20, // 4: cli.LoginResponse.User:type_name -> cli.User
	21, // 5: cli.LoginResponse.Char:type_name -> cli.Char
	22, // 6: cli.LoginResponse.Book:type_name -> cli.Book
	23, // 7: cli.LoginResponse.Config:type_name -> cli.HallConfig
	24, // 8: cli.LoginResponse.SigninAwardData:type_name -> cli.SigninAwardData
	25, // 9: cli.LoginResponse.MailList:type_name -> cli.MailItem
	26, // 10: cli.LoginResponse.CustomerList:type_name -> cli.CustomerItem
	27, // 11: cli.LoginResponse.PropList:type_name -> cli.Prop
	28, // 12: cli.LoginResponse.AddUpSigninAwardData:type_name -> cli.AddUpSigninAwardData
	29, // 13: cli.LoginResponse.ShopAdderData:type_name -> cli.ShopAdderData
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_hall_proto_init() }
func file_hall_proto_init() {
	if File_hall_proto != nil {
		return
	}
	file_structs_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_hall_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginConflictRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginConflictPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginBindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickOfflineReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForbidPlayerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForbidPlayerPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountKickPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountRejectPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hall_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionFailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hall_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hall_proto_goTypes,
		DependencyIndexes: file_hall_proto_depIdxs,
		MessageInfos:      file_hall_proto_msgTypes,
	}.Build()
	File_hall_proto = out.File
	file_hall_proto_rawDesc = nil
	file_hall_proto_goTypes = nil
	file_hall_proto_depIdxs = nil
}
