// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.0
// source: broad.proto

package cli

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BroadItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       int64  `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`            //广播类型,1提现走马灯,2赢取走马灯,3系统通知走马灯
	Content    string `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`       //走马灯内容
	GamePlay   string `protobuf:"bytes,3,opt,name=GamePlay,proto3" json:"GamePlay,omitempty"`     //触发场景(玩法名称，提现，系统)
	CoinCount  int64  `protobuf:"varint,4,opt,name=CoinCount,proto3" json:"CoinCount,omitempty"`  //触发金额
	PlayerID   int64  `protobuf:"varint,5,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`    //玩家ID
	PlayerIcon string `protobuf:"bytes,6,opt,name=PlayerIcon,proto3" json:"PlayerIcon,omitempty"` //玩家头像
	PlayerNick string `protobuf:"bytes,7,opt,name=PlayerNick,proto3" json:"PlayerNick,omitempty"` //玩家昵称
	AgentID    int64  `protobuf:"varint,8,opt,name=AgentID,proto3" json:"AgentID,omitempty"`      //玩家代理
}

func (x *BroadItem) Reset() {
	*x = BroadItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broad_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadItem) ProtoMessage() {}

func (x *BroadItem) ProtoReflect() protoreflect.Message {
	mi := &file_broad_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadItem.ProtoReflect.Descriptor instead.
func (*BroadItem) Descriptor() ([]byte, []int) {
	return file_broad_proto_rawDescGZIP(), []int{0}
}

func (x *BroadItem) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BroadItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BroadItem) GetGamePlay() string {
	if x != nil {
		return x.GamePlay
	}
	return ""
}

func (x *BroadItem) GetCoinCount() int64 {
	if x != nil {
		return x.CoinCount
	}
	return 0
}

func (x *BroadItem) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *BroadItem) GetPlayerIcon() string {
	if x != nil {
		return x.PlayerIcon
	}
	return ""
}

func (x *BroadItem) GetPlayerNick() string {
	if x != nil {
		return x.PlayerNick
	}
	return ""
}

func (x *BroadItem) GetAgentID() int64 {
	if x != nil {
		return x.AgentID
	}
	return 0
}

type OnlineBroadItemPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"BroadItemList"
	BroadItemList []*BroadItem `protobuf:"bytes,1,rep,name=BroadItemList,proto3" json:"BroadItemList,omitempty"` //广播
}

func (x *OnlineBroadItemPush) Reset() {
	*x = OnlineBroadItemPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_broad_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineBroadItemPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBroadItemPush) ProtoMessage() {}

func (x *OnlineBroadItemPush) ProtoReflect() protoreflect.Message {
	mi := &file_broad_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBroadItemPush.ProtoReflect.Descriptor instead.
func (*OnlineBroadItemPush) Descriptor() ([]byte, []int) {
	return file_broad_proto_rawDescGZIP(), []int{1}
}

func (x *OnlineBroadItemPush) GetBroadItemList() []*BroadItem {
	if x != nil {
		return x.BroadItemList
	}
	return nil
}

var File_broad_proto protoreflect.FileDescriptor

var file_broad_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63,
	0x6c, 0x69, 0x22, 0xe9, 0x01, 0x0a, 0x09, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f,
	0x69, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43,
	0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x63,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x63, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x69,
	0x63, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x4e, 0x69, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x4b,
	0x0a, 0x13, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x50, 0x75, 0x73, 0x68, 0x12, 0x34, 0x0a, 0x0d, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x49, 0x74,
	0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63,
	0x6c, 0x69, 0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0d, 0x42, 0x72,
	0x6f, 0x61, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x70,
	0x62, 0x2f, 0x63, 0x6c, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_broad_proto_rawDescOnce sync.Once
	file_broad_proto_rawDescData = file_broad_proto_rawDesc
)

func file_broad_proto_rawDescGZIP() []byte {
	file_broad_proto_rawDescOnce.Do(func() {
		file_broad_proto_rawDescData = protoimpl.X.CompressGZIP(file_broad_proto_rawDescData)
	})
	return file_broad_proto_rawDescData
}

var file_broad_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_broad_proto_goTypes = []interface{}{
	(*BroadItem)(nil),           // 0: cli.BroadItem
	(*OnlineBroadItemPush)(nil), // 1: cli.OnlineBroadItemPush
}
var file_broad_proto_depIdxs = []int32{
	0, // 0: cli.OnlineBroadItemPush.BroadItemList:type_name -> cli.BroadItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_broad_proto_init() }
func file_broad_proto_init() {
	if File_broad_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_broad_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_broad_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineBroadItemPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_broad_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_broad_proto_goTypes,
		DependencyIndexes: file_broad_proto_depIdxs,
		MessageInfos:      file_broad_proto_msgTypes,
	}.Build()
	File_broad_proto = out.File
	file_broad_proto_rawDesc = nil
	file_broad_proto_goTypes = nil
	file_broad_proto_depIdxs = nil
}
