// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.0
// source: invite.proto

package cli

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InviteAwardItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AwardType  string `protobuf:"bytes,1,opt,name=AwardType,proto3" json:"AwardType,omitempty"`   // 奖励类型 1:注册奖励 2:充值奖励
	AwardID    string `protobuf:"bytes,2,opt,name=AwardID,proto3" json:"AwardID,omitempty"`       // 奖励ID
	AwardTime  int64  `protobuf:"varint,3,opt,name=AwardTime,proto3" json:"AwardTime,omitempty"`  // 奖励时间
	Status     int64  `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`        // 奖励状态 0:限制条件未解除 1:可领取 2:领取过 3:已过期
	GameID     int64  `protobuf:"varint,5,opt,name=GameID,proto3" json:"GameID,omitempty"`        // 被邀请玩家ID
	PlayerName string `protobuf:"bytes,6,opt,name=PlayerName,proto3" json:"PlayerName,omitempty"` // 被邀请玩家名称
	PlayerID   int64  `protobuf:"varint,7,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`    // 被邀请玩家ID
	Bonus      int64  `protobuf:"varint,8,opt,name=Bonus,proto3" json:"Bonus,omitempty"`          // 奖励金额
	Recharge   int64  `protobuf:"varint,9,opt,name=Recharge,proto3" json:"Recharge,omitempty"`    // 充值金额
	Rebate     int64  `protobuf:"varint,10,opt,name=Rebate,proto3" json:"Rebate,omitempty"`       // 返利比例
	ID         int64  `protobuf:"varint,11,opt,name=ID,proto3" json:"ID,omitempty"`               // 该充值玩家的邀请人ID
}

func (x *InviteAwardItem) Reset() {
	*x = InviteAwardItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InviteAwardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteAwardItem) ProtoMessage() {}

func (x *InviteAwardItem) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteAwardItem.ProtoReflect.Descriptor instead.
func (*InviteAwardItem) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{0}
}

func (x *InviteAwardItem) GetAwardType() string {
	if x != nil {
		return x.AwardType
	}
	return ""
}

func (x *InviteAwardItem) GetAwardID() string {
	if x != nil {
		return x.AwardID
	}
	return ""
}

func (x *InviteAwardItem) GetAwardTime() int64 {
	if x != nil {
		return x.AwardTime
	}
	return 0
}

func (x *InviteAwardItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InviteAwardItem) GetGameID() int64 {
	if x != nil {
		return x.GameID
	}
	return 0
}

func (x *InviteAwardItem) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *InviteAwardItem) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *InviteAwardItem) GetBonus() int64 {
	if x != nil {
		return x.Bonus
	}
	return 0
}

func (x *InviteAwardItem) GetRecharge() int64 {
	if x != nil {
		return x.Recharge
	}
	return 0
}

func (x *InviteAwardItem) GetRebate() int64 {
	if x != nil {
		return x.Rebate
	}
	return 0
}

func (x *InviteAwardItem) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

// 邀请系统更新上线玩家
type OnlineUpdateInviterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"DirectUID"
	DirectUID int64 `protobuf:"varint,1,opt,name=DirectUID,proto3" json:"DirectUID,omitempty"` // 直接上线ID
	// @inject_tag: json:"IntervalUID"
	IntervalUID int64 `protobuf:"varint,2,opt,name=IntervalUID,proto3" json:"IntervalUID,omitempty"` // 上线的上线ID
}

func (x *OnlineUpdateInviterRequest) Reset() {
	*x = OnlineUpdateInviterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineUpdateInviterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUpdateInviterRequest) ProtoMessage() {}

func (x *OnlineUpdateInviterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUpdateInviterRequest.ProtoReflect.Descriptor instead.
func (*OnlineUpdateInviterRequest) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{1}
}

func (x *OnlineUpdateInviterRequest) GetDirectUID() int64 {
	if x != nil {
		return x.DirectUID
	}
	return 0
}

func (x *OnlineUpdateInviterRequest) GetIntervalUID() int64 {
	if x != nil {
		return x.IntervalUID
	}
	return 0
}

type OnlineUpdateInviterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *OnlineUpdateInviterResponse) Reset() {
	*x = OnlineUpdateInviterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineUpdateInviterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUpdateInviterResponse) ProtoMessage() {}

func (x *OnlineUpdateInviterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUpdateInviterResponse.ProtoReflect.Descriptor instead.
func (*OnlineUpdateInviterResponse) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{2}
}

func (x *OnlineUpdateInviterResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// 邀请系统查询状态
type OnlineQueryInviteStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnlineQueryInviteStatusRequest) Reset() {
	*x = OnlineQueryInviteStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineQueryInviteStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineQueryInviteStatusRequest) ProtoMessage() {}

func (x *OnlineQueryInviteStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineQueryInviteStatusRequest.ProtoReflect.Descriptor instead.
func (*OnlineQueryInviteStatusRequest) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{3}
}

type OnlineQueryInviteStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"InviteOpen"
	InviteOpen bool `protobuf:"varint,2,opt,name=InviteOpen,proto3" json:"InviteOpen,omitempty"` // 邀请奖励功能是否开启
	// @inject_tag: json:"CommissionOpen"
	CommissionOpen bool `protobuf:"varint,3,opt,name=CommissionOpen,proto3" json:"CommissionOpen,omitempty"` // 充值返利功能是否开启
	// @inject_tag: json:"ActivateCoin"
	ActivateCoin []int64 `protobuf:"varint,4,rep,packed,name=ActivateCoin,proto3" json:"ActivateCoin,omitempty"` // 激活奖励金额(x10000)
	// @inject_tag: json:"PaymentRate"
	PaymentRate []int64 `protobuf:"varint,5,rep,packed,name=PaymentRate,proto3" json:"PaymentRate,omitempty"` // 充值返利比例(x100)
	// @inject_tag: json:"TotalCoin"
	TotalCoin int64 `protobuf:"varint,6,opt,name=TotalCoin,proto3" json:"TotalCoin,omitempty"` // 累计获得奖励数量(x10000)
	// @inject_tag: json:"LockedCoin"
	LockedCoin int64 `protobuf:"varint,7,opt,name=LockedCoin,proto3" json:"LockedCoin,omitempty"` // 锁定的不可提现奖励数量(x10000)
	// @inject_tag: json:"WithdrawableCoin"
	WithdrawableCoin int64 `protobuf:"varint,8,opt,name=WithdrawableCoin,proto3" json:"WithdrawableCoin,omitempty"` // 没锁定的可提现数量(x10000)
}

func (x *OnlineQueryInviteStatusResponse) Reset() {
	*x = OnlineQueryInviteStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineQueryInviteStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineQueryInviteStatusResponse) ProtoMessage() {}

func (x *OnlineQueryInviteStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineQueryInviteStatusResponse.ProtoReflect.Descriptor instead.
func (*OnlineQueryInviteStatusResponse) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{4}
}

func (x *OnlineQueryInviteStatusResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineQueryInviteStatusResponse) GetInviteOpen() bool {
	if x != nil {
		return x.InviteOpen
	}
	return false
}

func (x *OnlineQueryInviteStatusResponse) GetCommissionOpen() bool {
	if x != nil {
		return x.CommissionOpen
	}
	return false
}

func (x *OnlineQueryInviteStatusResponse) GetActivateCoin() []int64 {
	if x != nil {
		return x.ActivateCoin
	}
	return nil
}

func (x *OnlineQueryInviteStatusResponse) GetPaymentRate() []int64 {
	if x != nil {
		return x.PaymentRate
	}
	return nil
}

func (x *OnlineQueryInviteStatusResponse) GetTotalCoin() int64 {
	if x != nil {
		return x.TotalCoin
	}
	return 0
}

func (x *OnlineQueryInviteStatusResponse) GetLockedCoin() int64 {
	if x != nil {
		return x.LockedCoin
	}
	return 0
}

func (x *OnlineQueryInviteStatusResponse) GetWithdrawableCoin() int64 {
	if x != nil {
		return x.WithdrawableCoin
	}
	return 0
}

// 邀请系统查询奖励记录列表
type OnlineQueryInviteRecordListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnlineQueryInviteRecordListRequest) Reset() {
	*x = OnlineQueryInviteRecordListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineQueryInviteRecordListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineQueryInviteRecordListRequest) ProtoMessage() {}

func (x *OnlineQueryInviteRecordListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineQueryInviteRecordListRequest.ProtoReflect.Descriptor instead.
func (*OnlineQueryInviteRecordListRequest) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{5}
}

type OnlineQueryInviteRecordListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"RegisterAwardList"
	RegisterAwardList []*InviteAwardItem `protobuf:"bytes,2,rep,name=RegisterAwardList,proto3" json:"RegisterAwardList,omitempty"` // 注册奖励记录
	// @inject_tag: json:"PaymentAwardList"
	PaymentAwardList []*InviteAwardItem `protobuf:"bytes,3,rep,name=PaymentAwardList,proto3" json:"PaymentAwardList,omitempty"` // 充值奖励记录
}

func (x *OnlineQueryInviteRecordListResponse) Reset() {
	*x = OnlineQueryInviteRecordListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineQueryInviteRecordListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineQueryInviteRecordListResponse) ProtoMessage() {}

func (x *OnlineQueryInviteRecordListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineQueryInviteRecordListResponse.ProtoReflect.Descriptor instead.
func (*OnlineQueryInviteRecordListResponse) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{6}
}

func (x *OnlineQueryInviteRecordListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineQueryInviteRecordListResponse) GetRegisterAwardList() []*InviteAwardItem {
	if x != nil {
		return x.RegisterAwardList
	}
	return nil
}

func (x *OnlineQueryInviteRecordListResponse) GetPaymentAwardList() []*InviteAwardItem {
	if x != nil {
		return x.PaymentAwardList
	}
	return nil
}

// 邀请系统奖励推送
type OnlineInviteAwardPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnlineInviteAwardPush) Reset() {
	*x = OnlineInviteAwardPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineInviteAwardPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineInviteAwardPush) ProtoMessage() {}

func (x *OnlineInviteAwardPush) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineInviteAwardPush.ProtoReflect.Descriptor instead.
func (*OnlineInviteAwardPush) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{7}
}

// 邀请系统领取奖励
type OnlineClaimInviteAwardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"AwardID"
	AwardID string `protobuf:"bytes,1,opt,name=AwardID,proto3" json:"AwardID,omitempty"` // 奖励ID
}

func (x *OnlineClaimInviteAwardRequest) Reset() {
	*x = OnlineClaimInviteAwardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineClaimInviteAwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineClaimInviteAwardRequest) ProtoMessage() {}

func (x *OnlineClaimInviteAwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineClaimInviteAwardRequest.ProtoReflect.Descriptor instead.
func (*OnlineClaimInviteAwardRequest) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{8}
}

func (x *OnlineClaimInviteAwardRequest) GetAwardID() string {
	if x != nil {
		return x.AwardID
	}
	return ""
}

type OnlineClaimInviteAwardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"AwardID"
	AwardID string `protobuf:"bytes,2,opt,name=AwardID,proto3" json:"AwardID,omitempty"` // 奖励ID
	// @inject_tag: json:"ClaimCoin"
	ClaimCoin int64 `protobuf:"varint,3,opt,name=ClaimCoin,proto3" json:"ClaimCoin,omitempty"` // 获得奖励
	// @inject_tag: json:"TotalCoin"
	TotalCoin int64 `protobuf:"varint,4,opt,name=TotalCoin,proto3" json:"TotalCoin,omitempty"` // 累计获得奖励
	// @inject_tag: json:"WithdrawCoin"
	WithdrawCoin int64 `protobuf:"varint,5,opt,name=WithdrawCoin,proto3" json:"WithdrawCoin,omitempty"` // 可提现金额
	// @inject_tag: json:"RegisterCanGetCount"
	RegisterCanGetCount int64 `protobuf:"varint,6,opt,name=RegisterCanGetCount,proto3" json:"RegisterCanGetCount,omitempty"` // 可以领取的注册奖励笔数
	// @inject_tag: json:"PaymentCanGetCount"
	PaymentCanGetCount int64 `protobuf:"varint,7,opt,name=PaymentCanGetCount,proto3" json:"PaymentCanGetCount,omitempty"` // 可以领取的充值奖励笔数
	// @inject_tag: json:"Coin"
	Coin int64 `protobuf:"varint,8,opt,name=Coin,proto3" json:"Coin,omitempty"` // 玩家最后的金币数
	// @inject_tag: json:"RankUpdated"
	RankUpdated bool `protobuf:"varint,9,opt,name=RankUpdated,proto3" json:"RankUpdated,omitempty"` // 排行榜是否变更
}

func (x *OnlineClaimInviteAwardResponse) Reset() {
	*x = OnlineClaimInviteAwardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineClaimInviteAwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineClaimInviteAwardResponse) ProtoMessage() {}

func (x *OnlineClaimInviteAwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineClaimInviteAwardResponse.ProtoReflect.Descriptor instead.
func (*OnlineClaimInviteAwardResponse) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{9}
}

func (x *OnlineClaimInviteAwardResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineClaimInviteAwardResponse) GetAwardID() string {
	if x != nil {
		return x.AwardID
	}
	return ""
}

func (x *OnlineClaimInviteAwardResponse) GetClaimCoin() int64 {
	if x != nil {
		return x.ClaimCoin
	}
	return 0
}

func (x *OnlineClaimInviteAwardResponse) GetTotalCoin() int64 {
	if x != nil {
		return x.TotalCoin
	}
	return 0
}

func (x *OnlineClaimInviteAwardResponse) GetWithdrawCoin() int64 {
	if x != nil {
		return x.WithdrawCoin
	}
	return 0
}

func (x *OnlineClaimInviteAwardResponse) GetRegisterCanGetCount() int64 {
	if x != nil {
		return x.RegisterCanGetCount
	}
	return 0
}

func (x *OnlineClaimInviteAwardResponse) GetPaymentCanGetCount() int64 {
	if x != nil {
		return x.PaymentCanGetCount
	}
	return 0
}

func (x *OnlineClaimInviteAwardResponse) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *OnlineClaimInviteAwardResponse) GetRankUpdated() bool {
	if x != nil {
		return x.RankUpdated
	}
	return false
}

// 邀请系统创建分享APK
type OnlineCreateAPKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Inviter"
	Inviter int64 `protobuf:"varint,1,opt,name=Inviter,proto3" json:"Inviter,omitempty"` // 直接上线ID
	// @inject_tag: json:"IntervalUID"
	Parent int64 `protobuf:"varint,2,opt,name=Parent,proto3" json:"Parent,omitempty"` // 上线的上线ID
}

func (x *OnlineCreateAPKRequest) Reset() {
	*x = OnlineCreateAPKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineCreateAPKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineCreateAPKRequest) ProtoMessage() {}

func (x *OnlineCreateAPKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineCreateAPKRequest.ProtoReflect.Descriptor instead.
func (*OnlineCreateAPKRequest) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{10}
}

func (x *OnlineCreateAPKRequest) GetInviter() int64 {
	if x != nil {
		return x.Inviter
	}
	return 0
}

func (x *OnlineCreateAPKRequest) GetParent() int64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

type OnlineCreateAPKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *OnlineCreateAPKResponse) Reset() {
	*x = OnlineCreateAPKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_invite_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineCreateAPKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineCreateAPKResponse) ProtoMessage() {}

func (x *OnlineCreateAPKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invite_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineCreateAPKResponse.ProtoReflect.Descriptor instead.
func (*OnlineCreateAPKResponse) Descriptor() ([]byte, []int) {
	return file_invite_proto_rawDescGZIP(), []int{11}
}

func (x *OnlineCreateAPKResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_invite_proto protoreflect.FileDescriptor

var file_invite_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x63, 0x6c, 0x69, 0x22, 0xad, 0x02, 0x0a, 0x0f, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x41, 0x77,
	0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x77, 0x61, 0x72, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x77, 0x61, 0x72,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x77, 0x61, 0x72, 0x64, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x77, 0x61, 0x72, 0x64, 0x49, 0x44, 0x12,
	0x1c, 0x0a, 0x09, 0x41, 0x77, 0x61, 0x72, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x41, 0x77, 0x61, 0x72, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x1e, 0x0a,
	0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x6f, 0x6e,
	0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x42, 0x6f, 0x6e, 0x75, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x52,
	0x65, 0x62, 0x61, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x52, 0x65, 0x62,
	0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x44, 0x22, 0x5c, 0x0a, 0x1a, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x55, 0x49, 0x44, 0x12,
	0x20, 0x0a, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x55, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x55, 0x49,
	0x44, 0x22, 0x31, 0x0a, 0x1b, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x20, 0x0a, 0x1e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xad, 0x02, 0x0a, 0x1f, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x26,
	0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x65, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0c, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x4c, 0x6f,
	0x63, 0x6b, 0x65, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x4c, 0x6f, 0x63, 0x6b, 0x65, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62,
	0x6c, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x22, 0x24, 0x0a, 0x22, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xbf, 0x01, 0x0a,
	0x23, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x42, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x41, 0x77, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x41, 0x77, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x41, 0x77, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x10,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x77, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x41, 0x77, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x10, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x77, 0x61, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x17,
	0x0a, 0x15, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x41, 0x77,
	0x61, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x22, 0x39, 0x0a, 0x1d, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x41, 0x77, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x77, 0x61, 0x72,
	0x64, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x77, 0x61, 0x72, 0x64,
	0x49, 0x44, 0x22, 0xc6, 0x02, 0x0a, 0x1e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x41, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x77, 0x61,
	0x72, 0x64, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x77, 0x61, 0x72,
	0x64, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x43, 0x6f, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x43, 0x6f, 0x69,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x69, 0x6e, 0x12,
	0x22, 0x0a, 0x0c, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x69, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x43,
	0x6f, 0x69, 0x6e, 0x12, 0x30, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43,
	0x61, 0x6e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x61, 0x6e, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x43, 0x61, 0x6e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x12, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x6e, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x52, 0x61, 0x6e,
	0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x52, 0x61, 0x6e, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x4a, 0x0a, 0x16, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x50, 0x4b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x72, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x22, 0x2d, 0x0a, 0x17, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x50, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_invite_proto_rawDescOnce sync.Once
	file_invite_proto_rawDescData = file_invite_proto_rawDesc
)

func file_invite_proto_rawDescGZIP() []byte {
	file_invite_proto_rawDescOnce.Do(func() {
		file_invite_proto_rawDescData = protoimpl.X.CompressGZIP(file_invite_proto_rawDescData)
	})
	return file_invite_proto_rawDescData
}

var file_invite_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_invite_proto_goTypes = []interface{}{
	(*InviteAwardItem)(nil),                     // 0: cli.InviteAwardItem
	(*OnlineUpdateInviterRequest)(nil),          // 1: cli.OnlineUpdateInviterRequest
	(*OnlineUpdateInviterResponse)(nil),         // 2: cli.OnlineUpdateInviterResponse
	(*OnlineQueryInviteStatusRequest)(nil),      // 3: cli.OnlineQueryInviteStatusRequest
	(*OnlineQueryInviteStatusResponse)(nil),     // 4: cli.OnlineQueryInviteStatusResponse
	(*OnlineQueryInviteRecordListRequest)(nil),  // 5: cli.OnlineQueryInviteRecordListRequest
	(*OnlineQueryInviteRecordListResponse)(nil), // 6: cli.OnlineQueryInviteRecordListResponse
	(*OnlineInviteAwardPush)(nil),               // 7: cli.OnlineInviteAwardPush
	(*OnlineClaimInviteAwardRequest)(nil),       // 8: cli.OnlineClaimInviteAwardRequest
	(*OnlineClaimInviteAwardResponse)(nil),      // 9: cli.OnlineClaimInviteAwardResponse
	(*OnlineCreateAPKRequest)(nil),              // 10: cli.OnlineCreateAPKRequest
	(*OnlineCreateAPKResponse)(nil),             // 11: cli.OnlineCreateAPKResponse
}
var file_invite_proto_depIdxs = []int32{
	0, // 0: cli.OnlineQueryInviteRecordListResponse.RegisterAwardList:type_name -> cli.InviteAwardItem
	0, // 1: cli.OnlineQueryInviteRecordListResponse.PaymentAwardList:type_name -> cli.InviteAwardItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_invite_proto_init() }
func file_invite_proto_init() {
	if File_invite_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_invite_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InviteAwardItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineUpdateInviterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineUpdateInviterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineQueryInviteStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineQueryInviteStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineQueryInviteRecordListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineQueryInviteRecordListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineInviteAwardPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineClaimInviteAwardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineClaimInviteAwardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineCreateAPKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_invite_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineCreateAPKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_invite_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invite_proto_goTypes,
		DependencyIndexes: file_invite_proto_depIdxs,
		MessageInfos:      file_invite_proto_msgTypes,
	}.Build()
	File_invite_proto = out.File
	file_invite_proto_rawDesc = nil
	file_invite_proto_goTypes = nil
	file_invite_proto_depIdxs = nil
}
