// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.0
// source: online.proto

package cli

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnlineBindAccessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
}

func (x *OnlineBindAccessRequest) Reset() {
	*x = OnlineBindAccessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineBindAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBindAccessRequest) ProtoMessage() {}

func (x *OnlineBindAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBindAccessRequest.ProtoReflect.Descriptor instead.
func (*OnlineBindAccessRequest) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{0}
}

func (x *OnlineBindAccessRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OnlineBindAccessRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type OnlineBindAccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"Acc"
	Acc *Acc `protobuf:"bytes,2,opt,name=Acc,proto3" json:"Acc,omitempty"`
}

func (x *OnlineBindAccessResponse) Reset() {
	*x = OnlineBindAccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineBindAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBindAccessResponse) ProtoMessage() {}

func (x *OnlineBindAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBindAccessResponse.ProtoReflect.Descriptor instead.
func (*OnlineBindAccessResponse) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{1}
}

func (x *OnlineBindAccessResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineBindAccessResponse) GetAcc() *Acc {
	if x != nil {
		return x.Acc
	}
	return nil
}

// 更新玩家
type UpdatePlayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"PlayerID"
	PlayerID int64 `protobuf:"varint,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
}

func (x *UpdatePlayerRequest) Reset() {
	*x = UpdatePlayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerRequest) ProtoMessage() {}

func (x *UpdatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePlayerRequest) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

type UpdatePlayerPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"PlayerID"
	PlayerID int64 `protobuf:"varint,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	// @inject_tag: json:"Coin"
	Coin int64 `protobuf:"varint,2,opt,name=Coin,proto3" json:"Coin,omitempty"`
}

func (x *UpdatePlayerPush) Reset() {
	*x = UpdatePlayerPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePlayerPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlayerPush) ProtoMessage() {}

func (x *UpdatePlayerPush) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlayerPush.ProtoReflect.Descriptor instead.
func (*UpdatePlayerPush) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{3}
}

func (x *UpdatePlayerPush) GetPlayerID() int64 {
	if x != nil {
		return x.PlayerID
	}
	return 0
}

func (x *UpdatePlayerPush) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

type OnlineClaimFacebookAwardPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Coin"
	AwardCoin int64 `protobuf:"varint,1,opt,name=AwardCoin,proto3" json:"AwardCoin,omitempty"`
	Coin      int64 `protobuf:"varint,2,opt,name=Coin,proto3" json:"Coin,omitempty"`
}

func (x *OnlineClaimFacebookAwardPush) Reset() {
	*x = OnlineClaimFacebookAwardPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineClaimFacebookAwardPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineClaimFacebookAwardPush) ProtoMessage() {}

func (x *OnlineClaimFacebookAwardPush) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineClaimFacebookAwardPush.ProtoReflect.Descriptor instead.
func (*OnlineClaimFacebookAwardPush) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{4}
}

func (x *OnlineClaimFacebookAwardPush) GetAwardCoin() int64 {
	if x != nil {
		return x.AwardCoin
	}
	return 0
}

func (x *OnlineClaimFacebookAwardPush) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

// OnlineQueryMailsRequest 查询邮件列表请求
type OnlineQueryMailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnlineQueryMailsRequest) Reset() {
	*x = OnlineQueryMailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineQueryMailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineQueryMailsRequest) ProtoMessage() {}

func (x *OnlineQueryMailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineQueryMailsRequest.ProtoReflect.Descriptor instead.
func (*OnlineQueryMailsRequest) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{5}
}

type OnlineQueryMailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"MailList"
	MailList []*MailItem `protobuf:"bytes,2,rep,name=MailList,proto3" json:"MailList,omitempty"`
}

func (x *OnlineQueryMailsResponse) Reset() {
	*x = OnlineQueryMailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineQueryMailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineQueryMailsResponse) ProtoMessage() {}

func (x *OnlineQueryMailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineQueryMailsResponse.ProtoReflect.Descriptor instead.
func (*OnlineQueryMailsResponse) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{6}
}

func (x *OnlineQueryMailsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineQueryMailsResponse) GetMailList() []*MailItem {
	if x != nil {
		return x.MailList
	}
	return nil
}

// OnlineClaimMailsRequest 领取邮件列表请求
type OnlineClaimMailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IDList []int64 `protobuf:"varint,1,rep,packed,name=IDList,proto3" json:"IDList,omitempty"`
}

func (x *OnlineClaimMailsRequest) Reset() {
	*x = OnlineClaimMailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineClaimMailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineClaimMailsRequest) ProtoMessage() {}

func (x *OnlineClaimMailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineClaimMailsRequest.ProtoReflect.Descriptor instead.
func (*OnlineClaimMailsRequest) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{7}
}

func (x *OnlineClaimMailsRequest) GetIDList() []int64 {
	if x != nil {
		return x.IDList
	}
	return nil
}

type OnlineClaimMailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"MailList"
	MailList []*MailItem `protobuf:"bytes,2,rep,name=MailList,proto3" json:"MailList,omitempty"`
	// @inject_tag: json:"ClaimCoin"
	ClaimCoin int64 `protobuf:"varint,3,opt,name=ClaimCoin,proto3" json:"ClaimCoin,omitempty"`
	// @inject_tag: json:"Coin"
	Coin int64 `protobuf:"varint,4,opt,name=Coin,proto3" json:"Coin,omitempty"`
}

func (x *OnlineClaimMailsResponse) Reset() {
	*x = OnlineClaimMailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineClaimMailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineClaimMailsResponse) ProtoMessage() {}

func (x *OnlineClaimMailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineClaimMailsResponse.ProtoReflect.Descriptor instead.
func (*OnlineClaimMailsResponse) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{8}
}

func (x *OnlineClaimMailsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineClaimMailsResponse) GetMailList() []*MailItem {
	if x != nil {
		return x.MailList
	}
	return nil
}

func (x *OnlineClaimMailsResponse) GetClaimCoin() int64 {
	if x != nil {
		return x.ClaimCoin
	}
	return 0
}

func (x *OnlineClaimMailsResponse) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

// OnlineDeleteMailsRequest 删除邮件列表请求
type OnlineDeleteMailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IDList []int64 `protobuf:"varint,1,rep,packed,name=IDList,proto3" json:"IDList,omitempty"`
}

func (x *OnlineDeleteMailsRequest) Reset() {
	*x = OnlineDeleteMailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineDeleteMailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineDeleteMailsRequest) ProtoMessage() {}

func (x *OnlineDeleteMailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineDeleteMailsRequest.ProtoReflect.Descriptor instead.
func (*OnlineDeleteMailsRequest) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{9}
}

func (x *OnlineDeleteMailsRequest) GetIDList() []int64 {
	if x != nil {
		return x.IDList
	}
	return nil
}

type OnlineDeleteMailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"MailList"
	MailList []*MailItem `protobuf:"bytes,2,rep,name=MailList,proto3" json:"MailList,omitempty"`
}

func (x *OnlineDeleteMailsResponse) Reset() {
	*x = OnlineDeleteMailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineDeleteMailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineDeleteMailsResponse) ProtoMessage() {}

func (x *OnlineDeleteMailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineDeleteMailsResponse.ProtoReflect.Descriptor instead.
func (*OnlineDeleteMailsResponse) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{10}
}

func (x *OnlineDeleteMailsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineDeleteMailsResponse) GetMailList() []*MailItem {
	if x != nil {
		return x.MailList
	}
	return nil
}

// OnlineReadMailsRequest 查看邮件列表请求
type OnlineReadMailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IDList []int64 `protobuf:"varint,1,rep,packed,name=IDList,proto3" json:"IDList,omitempty"`
}

func (x *OnlineReadMailsRequest) Reset() {
	*x = OnlineReadMailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineReadMailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineReadMailsRequest) ProtoMessage() {}

func (x *OnlineReadMailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineReadMailsRequest.ProtoReflect.Descriptor instead.
func (*OnlineReadMailsRequest) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{11}
}

func (x *OnlineReadMailsRequest) GetIDList() []int64 {
	if x != nil {
		return x.IDList
	}
	return nil
}

type OnlineReadMailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"MailList"
	MailList []*MailItem `protobuf:"bytes,2,rep,name=MailList,proto3" json:"MailList,omitempty"`
}

func (x *OnlineReadMailsResponse) Reset() {
	*x = OnlineReadMailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineReadMailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineReadMailsResponse) ProtoMessage() {}

func (x *OnlineReadMailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineReadMailsResponse.ProtoReflect.Descriptor instead.
func (*OnlineReadMailsResponse) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{12}
}

func (x *OnlineReadMailsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineReadMailsResponse) GetMailList() []*MailItem {
	if x != nil {
		return x.MailList
	}
	return nil
}

// OnlineMailsPush 收到新邮件
type OnlineMailsPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnlineMailsPush) Reset() {
	*x = OnlineMailsPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineMailsPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineMailsPush) ProtoMessage() {}

func (x *OnlineMailsPush) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineMailsPush.ProtoReflect.Descriptor instead.
func (*OnlineMailsPush) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{13}
}

// OnlineCustomerPush 客服列表变更
type OnlineCustomerPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnlineCustomerPush) Reset() {
	*x = OnlineCustomerPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineCustomerPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineCustomerPush) ProtoMessage() {}

func (x *OnlineCustomerPush) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineCustomerPush.ProtoReflect.Descriptor instead.
func (*OnlineCustomerPush) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{14}
}

// OnlineClientChangeModeRequest 客户端切前后台请求
type OnlineClientChangeModeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Background bool `protobuf:"varint,1,opt,name=Background,proto3" json:"Background,omitempty"`
}

func (x *OnlineClientChangeModeRequest) Reset() {
	*x = OnlineClientChangeModeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineClientChangeModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineClientChangeModeRequest) ProtoMessage() {}

func (x *OnlineClientChangeModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineClientChangeModeRequest.ProtoReflect.Descriptor instead.
func (*OnlineClientChangeModeRequest) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{15}
}

func (x *OnlineClientChangeModeRequest) GetBackground() bool {
	if x != nil {
		return x.Background
	}
	return false
}

type OnlineClientChangeModeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *OnlineClientChangeModeResponse) Reset() {
	*x = OnlineClientChangeModeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineClientChangeModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineClientChangeModeResponse) ProtoMessage() {}

func (x *OnlineClientChangeModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineClientChangeModeResponse.ProtoReflect.Descriptor instead.
func (*OnlineClientChangeModeResponse) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{16}
}

func (x *OnlineClientChangeModeResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type OnlineSetUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
}

func (x *OnlineSetUserRequest) Reset() {
	*x = OnlineSetUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineSetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineSetUserRequest) ProtoMessage() {}

func (x *OnlineSetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineSetUserRequest.ProtoReflect.Descriptor instead.
func (*OnlineSetUserRequest) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{17}
}

func (x *OnlineSetUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type OnlineSetUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	User *User `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
}

func (x *OnlineSetUserResponse) Reset() {
	*x = OnlineSetUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineSetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineSetUserResponse) ProtoMessage() {}

func (x *OnlineSetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineSetUserResponse.ProtoReflect.Descriptor instead.
func (*OnlineSetUserResponse) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{18}
}

func (x *OnlineSetUserResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineSetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type OnlineWatchAdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *OnlineWatchAdRequest) Reset() {
	*x = OnlineWatchAdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineWatchAdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineWatchAdRequest) ProtoMessage() {}

func (x *OnlineWatchAdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineWatchAdRequest.ProtoReflect.Descriptor instead.
func (*OnlineWatchAdRequest) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{19}
}

func (x *OnlineWatchAdRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type OnlineWatchAdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *OnlineWatchAdResponse) Reset() {
	*x = OnlineWatchAdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineWatchAdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineWatchAdResponse) ProtoMessage() {}

func (x *OnlineWatchAdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineWatchAdResponse.ProtoReflect.Descriptor instead.
func (*OnlineWatchAdResponse) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{20}
}

func (x *OnlineWatchAdResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type OnlineUpdateNetworkPromotionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NetworkPromotion string `protobuf:"bytes,1,opt,name=NetworkPromotion,proto3" json:"NetworkPromotion,omitempty"`
}

func (x *OnlineUpdateNetworkPromotionRequest) Reset() {
	*x = OnlineUpdateNetworkPromotionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineUpdateNetworkPromotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUpdateNetworkPromotionRequest) ProtoMessage() {}

func (x *OnlineUpdateNetworkPromotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUpdateNetworkPromotionRequest.ProtoReflect.Descriptor instead.
func (*OnlineUpdateNetworkPromotionRequest) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{21}
}

func (x *OnlineUpdateNetworkPromotionRequest) GetNetworkPromotion() string {
	if x != nil {
		return x.NetworkPromotion
	}
	return ""
}

type OnlineUpdateNetworkPromotionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"TagHub"
	TagHub string `protobuf:"bytes,2,opt,name=TagHub,proto3" json:"TagHub,omitempty"`
}

func (x *OnlineUpdateNetworkPromotionResponse) Reset() {
	*x = OnlineUpdateNetworkPromotionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineUpdateNetworkPromotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUpdateNetworkPromotionResponse) ProtoMessage() {}

func (x *OnlineUpdateNetworkPromotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUpdateNetworkPromotionResponse.ProtoReflect.Descriptor instead.
func (*OnlineUpdateNetworkPromotionResponse) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{22}
}

func (x *OnlineUpdateNetworkPromotionResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineUpdateNetworkPromotionResponse) GetTagHub() string {
	if x != nil {
		return x.TagHub
	}
	return ""
}

// 使用道具领取救济金请求 309
type OnlineBankruptGiftRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropID string `protobuf:"bytes,1,opt,name=PropID,proto3" json:"PropID,omitempty"` // 道具ID
}

func (x *OnlineBankruptGiftRequest) Reset() {
	*x = OnlineBankruptGiftRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineBankruptGiftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBankruptGiftRequest) ProtoMessage() {}

func (x *OnlineBankruptGiftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBankruptGiftRequest.ProtoReflect.Descriptor instead.
func (*OnlineBankruptGiftRequest) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{23}
}

func (x *OnlineBankruptGiftRequest) GetPropID() string {
	if x != nil {
		return x.PropID
	}
	return ""
}

// 使用道具领取救济金响应 412
type OnlineBankruptGiftResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code     int64   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	GiftCoin int64   `protobuf:"varint,2,opt,name=GiftCoin,proto3" json:"GiftCoin,omitempty"` // 救济金数量
	Coin     int64   `protobuf:"varint,3,opt,name=Coin,proto3" json:"Coin,omitempty"`         // 玩家最终金币数量
	PropList []*Prop `protobuf:"bytes,4,rep,name=PropList,proto3" json:"PropList,omitempty"`  // 道具列表
}

func (x *OnlineBankruptGiftResponse) Reset() {
	*x = OnlineBankruptGiftResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineBankruptGiftResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBankruptGiftResponse) ProtoMessage() {}

func (x *OnlineBankruptGiftResponse) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBankruptGiftResponse.ProtoReflect.Descriptor instead.
func (*OnlineBankruptGiftResponse) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{24}
}

func (x *OnlineBankruptGiftResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineBankruptGiftResponse) GetGiftCoin() int64 {
	if x != nil {
		return x.GiftCoin
	}
	return 0
}

func (x *OnlineBankruptGiftResponse) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *OnlineBankruptGiftResponse) GetPropList() []*Prop {
	if x != nil {
		return x.PropList
	}
	return nil
}

// 道具变化推送 413
type OnlinePropChangePush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropList []*Prop `protobuf:"bytes,1,rep,name=PropList,proto3" json:"PropList,omitempty"` // 道具列表
}

func (x *OnlinePropChangePush) Reset() {
	*x = OnlinePropChangePush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlinePropChangePush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePropChangePush) ProtoMessage() {}

func (x *OnlinePropChangePush) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePropChangePush.ProtoReflect.Descriptor instead.
func (*OnlinePropChangePush) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{25}
}

func (x *OnlinePropChangePush) GetPropList() []*Prop {
	if x != nil {
		return x.PropList
	}
	return nil
}

// 使用道具提高免费金币提现额度请求 310
type OnlineFreeWithdrawCreditRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropID string `protobuf:"bytes,1,opt,name=PropID,proto3" json:"PropID,omitempty"` // 道具ID
}

func (x *OnlineFreeWithdrawCreditRequest) Reset() {
	*x = OnlineFreeWithdrawCreditRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineFreeWithdrawCreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineFreeWithdrawCreditRequest) ProtoMessage() {}

func (x *OnlineFreeWithdrawCreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineFreeWithdrawCreditRequest.ProtoReflect.Descriptor instead.
func (*OnlineFreeWithdrawCreditRequest) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{26}
}

func (x *OnlineFreeWithdrawCreditRequest) GetPropID() string {
	if x != nil {
		return x.PropID
	}
	return ""
}

// 使用道具提高免费金币提现额度响应 414
type OnlineFreeWithdrawCreditResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code       int64   `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	GiftCredit int64   `protobuf:"varint,2,opt,name=GiftCredit,proto3" json:"GiftCredit,omitempty"` // 提升额度
	Credit     int64   `protobuf:"varint,3,opt,name=Credit,proto3" json:"Credit,omitempty"`         // 玩家最终额度
	PropList   []*Prop `protobuf:"bytes,4,rep,name=PropList,proto3" json:"PropList,omitempty"`      // 道具列表
}

func (x *OnlineFreeWithdrawCreditResponse) Reset() {
	*x = OnlineFreeWithdrawCreditResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineFreeWithdrawCreditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineFreeWithdrawCreditResponse) ProtoMessage() {}

func (x *OnlineFreeWithdrawCreditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineFreeWithdrawCreditResponse.ProtoReflect.Descriptor instead.
func (*OnlineFreeWithdrawCreditResponse) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{27}
}

func (x *OnlineFreeWithdrawCreditResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineFreeWithdrawCreditResponse) GetGiftCredit() int64 {
	if x != nil {
		return x.GiftCredit
	}
	return 0
}

func (x *OnlineFreeWithdrawCreditResponse) GetCredit() int64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

func (x *OnlineFreeWithdrawCreditResponse) GetPropList() []*Prop {
	if x != nil {
		return x.PropList
	}
	return nil
}

// 查询商城特惠商品状态请求 1171
type OnlineQueryShopAdderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OnlineQueryShopAdderRequest) Reset() {
	*x = OnlineQueryShopAdderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineQueryShopAdderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineQueryShopAdderRequest) ProtoMessage() {}

func (x *OnlineQueryShopAdderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineQueryShopAdderRequest.ProtoReflect.Descriptor instead.
func (*OnlineQueryShopAdderRequest) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{28}
}

// 查询商城特惠商品状态响应 1181
type OnlineQueryShopAdderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code          int64          `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	ShopAdderData *ShopAdderData `protobuf:"bytes,2,opt,name=ShopAdderData,proto3" json:"ShopAdderData,omitempty"` // 商城特惠商品状态
}

func (x *OnlineQueryShopAdderResponse) Reset() {
	*x = OnlineQueryShopAdderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_online_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineQueryShopAdderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineQueryShopAdderResponse) ProtoMessage() {}

func (x *OnlineQueryShopAdderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_online_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineQueryShopAdderResponse.ProtoReflect.Descriptor instead.
func (*OnlineQueryShopAdderResponse) Descriptor() ([]byte, []int) {
	return file_online_proto_rawDescGZIP(), []int{29}
}

func (x *OnlineQueryShopAdderResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OnlineQueryShopAdderResponse) GetShopAdderData() *ShopAdderData {
	if x != nil {
		return x.ShopAdderData
	}
	return nil
}

var File_online_proto protoreflect.FileDescriptor

var file_online_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x63, 0x6c, 0x69, 0x1a, 0x0d, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x47, 0x0a, 0x17, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x69, 0x6e, 0x64,
	0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4a, 0x0a, 0x18, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x03, 0x41,
	0x63, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x41,
	0x63, 0x63, 0x52, 0x03, 0x41, 0x63, 0x63, 0x22, 0x31, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x22, 0x42, 0x0a, 0x10, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x22, 0x50,
	0x0a, 0x1c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x46, 0x61, 0x63,
	0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x41, 0x77, 0x61, 0x72, 0x64, 0x50, 0x75, 0x73, 0x68, 0x12, 0x1c,
	0x0a, 0x09, 0x41, 0x77, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x41, 0x77, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x69, 0x6e,
	0x22, 0x19, 0x0a, 0x17, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x59, 0x0a, 0x18, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x4d,
	0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x63, 0x6c, 0x69, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x4d, 0x61,
	0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x17, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x06, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x8b, 0x01, 0x0a, 0x18, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x4d, 0x61,
	0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63,
	0x6c, 0x69, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x4d, 0x61, 0x69,
	0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x43, 0x6f,
	0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x43,
	0x6f, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x22, 0x32, 0x0a, 0x18, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x06, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5a, 0x0a, 0x19, 0x4f,
	0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x29, 0x0a, 0x08,
	0x4d, 0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x4d,
	0x61, 0x69, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x30, 0x0a, 0x16, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x06, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x58, 0x0a, 0x17, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x4d, 0x61, 0x69, 0x6c,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x6c, 0x69,
	0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x08, 0x4d, 0x61, 0x69, 0x6c, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x61, 0x69,
	0x6c, 0x73, 0x50, 0x75, 0x73, 0x68, 0x22, 0x14, 0x0a, 0x12, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x22, 0x3f, 0x0a, 0x1d,
	0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x34, 0x0a,
	0x1e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0x35, 0x0a, 0x14, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x6c, 0x69, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x22, 0x4a, 0x0a, 0x15, 0x4f, 0x6e,
	0x6c, 0x69, 0x6e, 0x65, 0x53, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x04, 0x55, 0x73, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x14, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x57, 0x61, 0x74, 0x63, 0x68, 0x41, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x2b, 0x0a, 0x15, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x57, 0x61, 0x74, 0x63,
	0x68, 0x41, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x51, 0x0a, 0x23, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72,
	0x6b, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x52, 0x0a, 0x24, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x54, 0x61, 0x67, 0x48, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x54, 0x61, 0x67, 0x48, 0x75, 0x62, 0x22, 0x33, 0x0a, 0x19, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x42, 0x61, 0x6e, 0x6b, 0x72, 0x75, 0x70, 0x74, 0x47, 0x69, 0x66, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x44, 0x22, 0x87, 0x01, 0x0a, 0x1a,
	0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x42, 0x61, 0x6e, 0x6b, 0x72, 0x75, 0x70, 0x74, 0x47, 0x69,
	0x66, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x47, 0x69, 0x66, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x47, 0x69, 0x66, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x25,
	0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x08, 0x50, 0x72, 0x6f,
	0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x3d, 0x0a, 0x14, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x50,
	0x72, 0x6f, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x75, 0x73, 0x68, 0x12, 0x25, 0x0a,
	0x08, 0x50, 0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x08, 0x50, 0x72, 0x6f, 0x70,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x1f, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x46, 0x72,
	0x65, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x6f, 0x70, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x44, 0x22,
	0x95, 0x01, 0x0a, 0x20, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x46, 0x72, 0x65, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x69, 0x66, 0x74,
	0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x47, 0x69,
	0x66, 0x74, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x64,
	0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74,
	0x12, 0x25, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x52, 0x08, 0x50,
	0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x4f, 0x6e, 0x6c, 0x69, 0x6e,
	0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x41, 0x64, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6c, 0x0a, 0x1c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x68, 0x6f, 0x70, 0x41, 0x64, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x0d, 0x53, 0x68,
	0x6f, 0x70, 0x41, 0x64, 0x64, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x41, 0x64, 0x64, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0d, 0x53, 0x68, 0x6f, 0x70, 0x41, 0x64, 0x64, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x62, 0x2f, 0x63, 0x6c, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_online_proto_rawDescOnce sync.Once
	file_online_proto_rawDescData = file_online_proto_rawDesc
)

func file_online_proto_rawDescGZIP() []byte {
	file_online_proto_rawDescOnce.Do(func() {
		file_online_proto_rawDescData = protoimpl.X.CompressGZIP(file_online_proto_rawDescData)
	})
	return file_online_proto_rawDescData
}

var file_online_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_online_proto_goTypes = []interface{}{
	(*OnlineBindAccessRequest)(nil),              // 0: cli.OnlineBindAccessRequest
	(*OnlineBindAccessResponse)(nil),             // 1: cli.OnlineBindAccessResponse
	(*UpdatePlayerRequest)(nil),                  // 2: cli.UpdatePlayerRequest
	(*UpdatePlayerPush)(nil),                     // 3: cli.UpdatePlayerPush
	(*OnlineClaimFacebookAwardPush)(nil),         // 4: cli.OnlineClaimFacebookAwardPush
	(*OnlineQueryMailsRequest)(nil),              // 5: cli.OnlineQueryMailsRequest
	(*OnlineQueryMailsResponse)(nil),             // 6: cli.OnlineQueryMailsResponse
	(*OnlineClaimMailsRequest)(nil),              // 7: cli.OnlineClaimMailsRequest
	(*OnlineClaimMailsResponse)(nil),             // 8: cli.OnlineClaimMailsResponse
	(*OnlineDeleteMailsRequest)(nil),             // 9: cli.OnlineDeleteMailsRequest
	(*OnlineDeleteMailsResponse)(nil),            // 10: cli.OnlineDeleteMailsResponse
	(*OnlineReadMailsRequest)(nil),               // 11: cli.OnlineReadMailsRequest
	(*OnlineReadMailsResponse)(nil),              // 12: cli.OnlineReadMailsResponse
	(*OnlineMailsPush)(nil),                      // 13: cli.OnlineMailsPush
	(*OnlineCustomerPush)(nil),                   // 14: cli.OnlineCustomerPush
	(*OnlineClientChangeModeRequest)(nil),        // 15: cli.OnlineClientChangeModeRequest
	(*OnlineClientChangeModeResponse)(nil),       // 16: cli.OnlineClientChangeModeResponse
	(*OnlineSetUserRequest)(nil),                 // 17: cli.OnlineSetUserRequest
	(*OnlineSetUserResponse)(nil),                // 18: cli.OnlineSetUserResponse
	(*OnlineWatchAdRequest)(nil),                 // 19: cli.OnlineWatchAdRequest
	(*OnlineWatchAdResponse)(nil),                // 20: cli.OnlineWatchAdResponse
	(*OnlineUpdateNetworkPromotionRequest)(nil),  // 21: cli.OnlineUpdateNetworkPromotionRequest
	(*OnlineUpdateNetworkPromotionResponse)(nil), // 22: cli.OnlineUpdateNetworkPromotionResponse
	(*OnlineBankruptGiftRequest)(nil),            // 23: cli.OnlineBankruptGiftRequest
	(*OnlineBankruptGiftResponse)(nil),           // 24: cli.OnlineBankruptGiftResponse
	(*OnlinePropChangePush)(nil),                 // 25: cli.OnlinePropChangePush
	(*OnlineFreeWithdrawCreditRequest)(nil),      // 26: cli.OnlineFreeWithdrawCreditRequest
	(*OnlineFreeWithdrawCreditResponse)(nil),     // 27: cli.OnlineFreeWithdrawCreditResponse
	(*OnlineQueryShopAdderRequest)(nil),          // 28: cli.OnlineQueryShopAdderRequest
	(*OnlineQueryShopAdderResponse)(nil),         // 29: cli.OnlineQueryShopAdderResponse
	(*Acc)(nil),                                  // 30: cli.Acc
	(*MailItem)(nil),                             // 31: cli.MailItem
	(*User)(nil),                                 // 32: cli.User
	(*Prop)(nil),                                 // 33: cli.Prop
	(*ShopAdderData)(nil),                        // 34: cli.ShopAdderData
}
var file_online_proto_depIdxs = []int32{
	30, // 0: cli.OnlineBindAccessResponse.Acc:type_name -> cli.Acc
	31, // 1: cli.OnlineQueryMailsResponse.MailList:type_name -> cli.MailItem
	31, // 2: cli.OnlineClaimMailsResponse.MailList:type_name -> cli.MailItem
	31, // 3: cli.OnlineDeleteMailsResponse.MailList:type_name -> cli.MailItem
	31, // 4: cli.OnlineReadMailsResponse.MailList:type_name -> cli.MailItem
	32, // 5: cli.OnlineSetUserRequest.User:type_name -> cli.User
	32, // 6: cli.OnlineSetUserResponse.User:type_name -> cli.User
	33, // 7: cli.OnlineBankruptGiftResponse.PropList:type_name -> cli.Prop
	33, // 8: cli.OnlinePropChangePush.PropList:type_name -> cli.Prop
	33, // 9: cli.OnlineFreeWithdrawCreditResponse.PropList:type_name -> cli.Prop
	34, // 10: cli.OnlineQueryShopAdderResponse.ShopAdderData:type_name -> cli.ShopAdderData
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_online_proto_init() }
func file_online_proto_init() {
	if File_online_proto != nil {
		return
	}
	file_structs_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_online_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineBindAccessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineBindAccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePlayerPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineClaimFacebookAwardPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineQueryMailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineQueryMailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineClaimMailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineClaimMailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineDeleteMailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineDeleteMailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineReadMailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineReadMailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineMailsPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineCustomerPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineClientChangeModeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineClientChangeModeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineSetUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineSetUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineWatchAdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineWatchAdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineUpdateNetworkPromotionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineUpdateNetworkPromotionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineBankruptGiftRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineBankruptGiftResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlinePropChangePush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineFreeWithdrawCreditRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineFreeWithdrawCreditResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineQueryShopAdderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_online_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineQueryShopAdderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_online_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_online_proto_goTypes,
		DependencyIndexes: file_online_proto_depIdxs,
		MessageInfos:      file_online_proto_msgTypes,
	}.Build()
	File_online_proto = out.File
	file_online_proto_rawDesc = nil
	file_online_proto_goTypes = nil
	file_online_proto_depIdxs = nil
}
