// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.0
// source: payment.proto

package cli

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PaymentCreateOrderRequest 生成支付订单ID请求 505
type PaymentOrderIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"PackageName"
	PackageName string `protobuf:"bytes,1,opt,name=PackageName,proto3" json:"PackageName,omitempty"` // 包名
	// @inject_tag: json:"Channel"
	Channel string `protobuf:"bytes,2,opt,name=Channel,proto3" json:"Channel,omitempty"` // 渠道
	// @inject_tag: json:"Entry"
	Entry string `protobuf:"bytes,3,opt,name=Entry,proto3" json:"Entry,omitempty"` // 支付场景(Bankrupt-破产,Prop-道具加成,Normal-商城与首冲)
	// @inject_tag: json:"Source"
	Source string `protobuf:"bytes,4,opt,name=Source,proto3" json:"Source,omitempty"` // 支付环境
	// @inject_tag: json:"PropID"
	PropID string `protobuf:"bytes,5,opt,name=PropID,proto3" json:"PropID,omitempty"` // 道具ID
}

func (x *PaymentOrderIDRequest) Reset() {
	*x = PaymentOrderIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentOrderIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentOrderIDRequest) ProtoMessage() {}

func (x *PaymentOrderIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentOrderIDRequest.ProtoReflect.Descriptor instead.
func (*PaymentOrderIDRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentOrderIDRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *PaymentOrderIDRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PaymentOrderIDRequest) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *PaymentOrderIDRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PaymentOrderIDRequest) GetPropID() string {
	if x != nil {
		return x.PropID
	}
	return ""
}

// PaymentOrderIDResponse 生成支付订单ID响应 557
type PaymentOrderIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"OrderID"
	OrderID string `protobuf:"bytes,2,opt,name=OrderID,proto3" json:"OrderID,omitempty"` // 订单ID
	// @inject_tag: json:"Multi"
	Multi int64 `protobuf:"varint,3,opt,name=Multi,proto3" json:"Multi,omitempty"` // 充值倍数(x100)
}

func (x *PaymentOrderIDResponse) Reset() {
	*x = PaymentOrderIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentOrderIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentOrderIDResponse) ProtoMessage() {}

func (x *PaymentOrderIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentOrderIDResponse.ProtoReflect.Descriptor instead.
func (*PaymentOrderIDResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PaymentOrderIDResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PaymentOrderIDResponse) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *PaymentOrderIDResponse) GetMulti() int64 {
	if x != nil {
		return x.Multi
	}
	return 0
}

// PaymentCreateOrderRequest 三方支付下单请求
type PaymentCreateOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"PackageName"
	PackageName string `protobuf:"bytes,1,opt,name=PackageName,proto3" json:"PackageName,omitempty"` // 包名
	// @inject_tag: json:"Channel"
	Channel string `protobuf:"bytes,2,opt,name=Channel,proto3" json:"Channel,omitempty"` // 渠道
	// @inject_tag: json:"Entry"
	Entry string `protobuf:"bytes,3,opt,name=Entry,proto3" json:"Entry,omitempty"` // 支付场景
	// @inject_tag: json:"Type"
	Type string `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"` // 付款方式(Google,Pix)
	// @inject_tag: json:"GoodsID"
	GoodsID string `protobuf:"bytes,5,opt,name=GoodsID,proto3" json:"GoodsID,omitempty"` // 商品ID
	// @inject_tag: json:"Extra"
	Extra string `protobuf:"bytes,6,opt,name=Extra,proto3" json:"Extra,omitempty"` // 附加信息
	// @inject_tag: json:"Source"
	Source string `protobuf:"bytes,7,opt,name=Source,proto3" json:"Source,omitempty"` // 支付环境
	// @inject_tag: json:"OrderID"
	OrderID string `protobuf:"bytes,8,opt,name=OrderID,proto3" json:"OrderID,omitempty"` // 订单ID
}

func (x *PaymentCreateOrderRequest) Reset() {
	*x = PaymentCreateOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentCreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreateOrderRequest) ProtoMessage() {}

func (x *PaymentCreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreateOrderRequest.ProtoReflect.Descriptor instead.
func (*PaymentCreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *PaymentCreateOrderRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *PaymentCreateOrderRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PaymentCreateOrderRequest) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *PaymentCreateOrderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PaymentCreateOrderRequest) GetGoodsID() string {
	if x != nil {
		return x.GoodsID
	}
	return ""
}

func (x *PaymentCreateOrderRequest) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *PaymentCreateOrderRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PaymentCreateOrderRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

type PaymentCreateOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *PaymentCreateOrderResponse) Reset() {
	*x = PaymentCreateOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentCreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreateOrderResponse) ProtoMessage() {}

func (x *PaymentCreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreateOrderResponse.ProtoReflect.Descriptor instead.
func (*PaymentCreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentCreateOrderResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// PaymentCustomCreateOrderRequest 三方自定义支付下单请求
type PaymentCustomCreateOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"PackageName"
	PackageName string `protobuf:"bytes,1,opt,name=PackageName,proto3" json:"PackageName,omitempty"` // 包名
	// @inject_tag: json:"Channel"
	Channel string `protobuf:"bytes,2,opt,name=Channel,proto3" json:"Channel,omitempty"` // 渠道
	// @inject_tag: json:"Entry"
	Entry string `protobuf:"bytes,3,opt,name=Entry,proto3" json:"Entry,omitempty"` // 支付场景
	// @inject_tag: json:"Type"
	Type string `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"` // 付款方式(Google,Pix,CashApp)
	// @inject_tag: json:"GoodsID"
	Pay int64 `protobuf:"varint,5,opt,name=Pay,proto3" json:"Pay,omitempty"` // 支付金额(*10000)
	// @inject_tag: json:"Extra"
	Extra string `protobuf:"bytes,6,opt,name=Extra,proto3" json:"Extra,omitempty"` // 附加信息
	// @inject_tag: json:"Source"
	Source string `protobuf:"bytes,7,opt,name=Source,proto3" json:"Source,omitempty"` // 支付环境
	// @inject_tag: json:"OrderID"
	OrderID string `protobuf:"bytes,8,opt,name=OrderID,proto3" json:"OrderID,omitempty"` // 订单ID
}

func (x *PaymentCustomCreateOrderRequest) Reset() {
	*x = PaymentCustomCreateOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentCustomCreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCustomCreateOrderRequest) ProtoMessage() {}

func (x *PaymentCustomCreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCustomCreateOrderRequest.ProtoReflect.Descriptor instead.
func (*PaymentCustomCreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *PaymentCustomCreateOrderRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *PaymentCustomCreateOrderRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PaymentCustomCreateOrderRequest) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *PaymentCustomCreateOrderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PaymentCustomCreateOrderRequest) GetPay() int64 {
	if x != nil {
		return x.Pay
	}
	return 0
}

func (x *PaymentCustomCreateOrderRequest) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *PaymentCustomCreateOrderRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PaymentCustomCreateOrderRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

type PaymentCustomCreateOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *PaymentCustomCreateOrderResponse) Reset() {
	*x = PaymentCustomCreateOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentCustomCreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCustomCreateOrderResponse) ProtoMessage() {}

func (x *PaymentCustomCreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCustomCreateOrderResponse.ProtoReflect.Descriptor instead.
func (*PaymentCustomCreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *PaymentCustomCreateOrderResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// PaymentPurchaseRequest Google支付发货请求
type PaymentPurchaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PackageName   string `protobuf:"bytes,1,opt,name=PackageName,proto3" json:"PackageName,omitempty"`
	Channel       string `protobuf:"bytes,2,opt,name=Channel,proto3" json:"Channel,omitempty"`
	Entry         string `protobuf:"bytes,3,opt,name=Entry,proto3" json:"Entry,omitempty"` // 支付场景
	Type          string `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	GoodsID       string `protobuf:"bytes,5,opt,name=GoodsID,proto3" json:"GoodsID,omitempty"`
	Extra         string `protobuf:"bytes,6,opt,name=Extra,proto3" json:"Extra,omitempty"`
	Source        string `protobuf:"bytes,7,opt,name=Source,proto3" json:"Source,omitempty"`
	OrderID       string `protobuf:"bytes,8,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	TransactionID string `protobuf:"bytes,9,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	Payload       string `protobuf:"bytes,10,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *PaymentPurchaseRequest) Reset() {
	*x = PaymentPurchaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentPurchaseRequest) ProtoMessage() {}

func (x *PaymentPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentPurchaseRequest.ProtoReflect.Descriptor instead.
func (*PaymentPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{6}
}

func (x *PaymentPurchaseRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *PaymentPurchaseRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PaymentPurchaseRequest) GetEntry() string {
	if x != nil {
		return x.Entry
	}
	return ""
}

func (x *PaymentPurchaseRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PaymentPurchaseRequest) GetGoodsID() string {
	if x != nil {
		return x.GoodsID
	}
	return ""
}

func (x *PaymentPurchaseRequest) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *PaymentPurchaseRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *PaymentPurchaseRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *PaymentPurchaseRequest) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

func (x *PaymentPurchaseRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type PaymentPurchaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code          int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	ProductID     string `protobuf:"bytes,2,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	GoodsID       string `protobuf:"bytes,3,opt,name=GoodsID,proto3" json:"GoodsID,omitempty"`
	SeqID         string `protobuf:"bytes,4,opt,name=SeqID,proto3" json:"SeqID,omitempty"`
	TransactionID string `protobuf:"bytes,5,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	Extra         string `protobuf:"bytes,6,opt,name=Extra,proto3" json:"Extra,omitempty"`
}

func (x *PaymentPurchaseResponse) Reset() {
	*x = PaymentPurchaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentPurchaseResponse) ProtoMessage() {}

func (x *PaymentPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentPurchaseResponse.ProtoReflect.Descriptor instead.
func (*PaymentPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{7}
}

func (x *PaymentPurchaseResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PaymentPurchaseResponse) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *PaymentPurchaseResponse) GetGoodsID() string {
	if x != nil {
		return x.GoodsID
	}
	return ""
}

func (x *PaymentPurchaseResponse) GetSeqID() string {
	if x != nil {
		return x.SeqID
	}
	return ""
}

func (x *PaymentPurchaseResponse) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

func (x *PaymentPurchaseResponse) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type PaymentPurchaseSuccessPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"PurchaseCoin"
	PurchaseCoin int64 `protobuf:"varint,1,opt,name=PurchaseCoin,proto3" json:"PurchaseCoin,omitempty"` // 本次购买获得的金币数
	// @inject_tag: json:"Coin"
	Coin int64 `protobuf:"varint,2,opt,name=Coin,proto3" json:"Coin,omitempty"` // 最终的金币数
	// @inject_tag: json:"OrderID"
	OrderID string `protobuf:"bytes,3,opt,name=OrderID,proto3" json:"OrderID,omitempty"` // 支付订单ID
	// @inject_tag: json:"PaymentType"
	PaymentType string `protobuf:"bytes,4,opt,name=PaymentType,proto3" json:"PaymentType,omitempty"` // 支付类型
	// @inject_tag: json:"GoodsID"
	GoodsID string `protobuf:"bytes,5,opt,name=GoodsID,proto3" json:"GoodsID,omitempty"` // 商品ID
	// @inject_tag: json:"AggIncRechargeCoin"
	AggIncRechargeCoin int64 `protobuf:"varint,6,opt,name=AggIncRechargeCoin,proto3" json:"AggIncRechargeCoin,omitempty"` //累计充值
	// @inject_tag: json:"PaymentCount"
	PaymentCount int64 `protobuf:"varint,7,opt,name=PaymentCount,proto3" json:"PaymentCount,omitempty"` // 支付金额(x10000)
	// @inject_tag: json:"ClaimPropList"
	ClaimPropList []*Prop `protobuf:"bytes,8,rep,name=ClaimPropList,proto3" json:"ClaimPropList,omitempty"` // 购买的道具列表
}

func (x *PaymentPurchaseSuccessPush) Reset() {
	*x = PaymentPurchaseSuccessPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentPurchaseSuccessPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentPurchaseSuccessPush) ProtoMessage() {}

func (x *PaymentPurchaseSuccessPush) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentPurchaseSuccessPush.ProtoReflect.Descriptor instead.
func (*PaymentPurchaseSuccessPush) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentPurchaseSuccessPush) GetPurchaseCoin() int64 {
	if x != nil {
		return x.PurchaseCoin
	}
	return 0
}

func (x *PaymentPurchaseSuccessPush) GetCoin() int64 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *PaymentPurchaseSuccessPush) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *PaymentPurchaseSuccessPush) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *PaymentPurchaseSuccessPush) GetGoodsID() string {
	if x != nil {
		return x.GoodsID
	}
	return ""
}

func (x *PaymentPurchaseSuccessPush) GetAggIncRechargeCoin() int64 {
	if x != nil {
		return x.AggIncRechargeCoin
	}
	return 0
}

func (x *PaymentPurchaseSuccessPush) GetPaymentCount() int64 {
	if x != nil {
		return x.PaymentCount
	}
	return 0
}

func (x *PaymentPurchaseSuccessPush) GetClaimPropList() []*Prop {
	if x != nil {
		return x.ClaimPropList
	}
	return nil
}

type PaymentCreateOrderPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"PayURL"
	PayURL string `protobuf:"bytes,2,opt,name=PayURL,proto3" json:"PayURL,omitempty"` // 支付链接
	// @inject_tag: json:"OrderID"
	OrderID string `protobuf:"bytes,3,opt,name=OrderID,proto3" json:"OrderID,omitempty"` // 支付订单ID
	// @inject_tag: json:"Platform"
	Platform string `protobuf:"bytes,4,opt,name=Platform,proto3" json:"Platform,omitempty"` // 支付平台
	// @inject_tag: json:"External"
	External bool `protobuf:"varint,5,opt,name=External,proto3" json:"External,omitempty"` // 是否使用外部浏览器
	// @inject_tag: json:"NotifyURL"
	NotifyURL string `protobuf:"bytes,6,opt,name=NotifyURL,proto3" json:"NotifyURL,omitempty"` // 回调链接
	// @inject_tag: json:"QRData"
	QRData string `protobuf:"bytes,7,opt,name=QRData,proto3" json:"QRData,omitempty"` // 二维码数据
	// @inject_tag: json:"PixData"
	PixData string `protobuf:"bytes,8,opt,name=PixData,proto3" json:"PixData,omitempty"` // Pix支付数据
	// @inject_tag: json:"UseQR"
	UseQR bool `protobuf:"varint,9,opt,name=UseQR,proto3" json:"UseQR,omitempty"` // 是否使用二维码支付
	// @inject_tag: json:"ExpireTime"
	ExpireTime int64 `protobuf:"varint,10,opt,name=ExpireTime,proto3" json:"ExpireTime,omitempty"` // 过期时间
}

func (x *PaymentCreateOrderPush) Reset() {
	*x = PaymentCreateOrderPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentCreateOrderPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreateOrderPush) ProtoMessage() {}

func (x *PaymentCreateOrderPush) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreateOrderPush.ProtoReflect.Descriptor instead.
func (*PaymentCreateOrderPush) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{9}
}

func (x *PaymentCreateOrderPush) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PaymentCreateOrderPush) GetPayURL() string {
	if x != nil {
		return x.PayURL
	}
	return ""
}

func (x *PaymentCreateOrderPush) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *PaymentCreateOrderPush) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PaymentCreateOrderPush) GetExternal() bool {
	if x != nil {
		return x.External
	}
	return false
}

func (x *PaymentCreateOrderPush) GetNotifyURL() string {
	if x != nil {
		return x.NotifyURL
	}
	return ""
}

func (x *PaymentCreateOrderPush) GetQRData() string {
	if x != nil {
		return x.QRData
	}
	return ""
}

func (x *PaymentCreateOrderPush) GetPixData() string {
	if x != nil {
		return x.PixData
	}
	return ""
}

func (x *PaymentCreateOrderPush) GetUseQR() bool {
	if x != nil {
		return x.UseQR
	}
	return false
}

func (x *PaymentCreateOrderPush) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

// PaymentQueryRecordListRequest 查询充值记录请求
type PaymentQueryRecordListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PaymentQueryRecordListRequest) Reset() {
	*x = PaymentQueryRecordListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentQueryRecordListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentQueryRecordListRequest) ProtoMessage() {}

func (x *PaymentQueryRecordListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentQueryRecordListRequest.ProtoReflect.Descriptor instead.
func (*PaymentQueryRecordListRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{10}
}

type PaymentQueryRecordListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"RecordList"
	RecordList []*CoinRecord `protobuf:"bytes,2,rep,name=RecordList,proto3" json:"RecordList,omitempty"`
}

func (x *PaymentQueryRecordListResponse) Reset() {
	*x = PaymentQueryRecordListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payment_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaymentQueryRecordListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentQueryRecordListResponse) ProtoMessage() {}

func (x *PaymentQueryRecordListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentQueryRecordListResponse.ProtoReflect.Descriptor instead.
func (*PaymentQueryRecordListResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{11}
}

func (x *PaymentQueryRecordListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PaymentQueryRecordListResponse) GetRecordList() []*CoinRecord {
	if x != nil {
		return x.RecordList
	}
	return nil
}

var File_payment_proto protoreflect.FileDescriptor

var file_payment_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x63, 0x6c, 0x69, 0x1a, 0x0d, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x99, 0x01, 0x0a, 0x15, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x6f, 0x70, 0x49,
	0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x44, 0x22,
	0x5c, 0x0a, 0x16, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x22, 0xe3, 0x01,
	0x0a, 0x19, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x78, 0x74, 0x72, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x78, 0x74, 0x72,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x30, 0x0a, 0x1a, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xe1, 0x01, 0x0a, 0x1f, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x50, 0x61, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x50, 0x61,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x22, 0x36, 0x0a, 0x20, 0x50, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0xa0, 0x02, 0x0a, 0x16, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x78, 0x74,
	0x72, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x22, 0xb7, 0x01, 0x0a, 0x17, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x65, 0x71, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x65, 0x71,
	0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x78, 0x74, 0x72,
	0x61, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x78, 0x74, 0x72, 0x61, 0x22, 0xaf,
	0x02, 0x0a, 0x1a, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61,
	0x73, 0x65, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x50, 0x75, 0x73, 0x68, 0x12, 0x22, 0x0a,
	0x0c, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x43, 0x6f, 0x69,
	0x6e, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x20, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x47, 0x6f, 0x6f, 0x64, 0x73, 0x49, 0x44, 0x12, 0x2e, 0x0a, 0x12, 0x41,
	0x67, 0x67, 0x49, 0x6e, 0x63, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x43, 0x6f, 0x69,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x41, 0x67, 0x67, 0x49, 0x6e, 0x63, 0x52,
	0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x50,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x2f, 0x0a, 0x0d, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x50, 0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x50, 0x72, 0x6f,
	0x70, 0x52, 0x0d, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x50, 0x72, 0x6f, 0x70, 0x4c, 0x69, 0x73, 0x74,
	0x22, 0x9c, 0x02, 0x0a, 0x16, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x61, 0x79, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x50, 0x61, 0x79, 0x55, 0x52, 0x4c, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1a, 0x0a,
	0x08, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x55, 0x52, 0x4c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x0a, 0x06, 0x51, 0x52, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x51, 0x52, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x18, 0x0a, 0x07, 0x50, 0x69, 0x78, 0x44, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x50, 0x69, 0x78, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x55, 0x73, 0x65,
	0x51, 0x52, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x55, 0x73, 0x65, 0x51, 0x52, 0x12,
	0x1e, 0x0a, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22,
	0x1f, 0x0a, 0x1d, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x65, 0x0a, 0x1e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6c, 0x69,
	0x2e, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x62, 0x2f, 0x63, 0x6c,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData = file_payment_proto_rawDesc
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(file_payment_proto_rawDescData)
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_payment_proto_goTypes = []interface{}{
	(*PaymentOrderIDRequest)(nil),            // 0: cli.PaymentOrderIDRequest
	(*PaymentOrderIDResponse)(nil),           // 1: cli.PaymentOrderIDResponse
	(*PaymentCreateOrderRequest)(nil),        // 2: cli.PaymentCreateOrderRequest
	(*PaymentCreateOrderResponse)(nil),       // 3: cli.PaymentCreateOrderResponse
	(*PaymentCustomCreateOrderRequest)(nil),  // 4: cli.PaymentCustomCreateOrderRequest
	(*PaymentCustomCreateOrderResponse)(nil), // 5: cli.PaymentCustomCreateOrderResponse
	(*PaymentPurchaseRequest)(nil),           // 6: cli.PaymentPurchaseRequest
	(*PaymentPurchaseResponse)(nil),          // 7: cli.PaymentPurchaseResponse
	(*PaymentPurchaseSuccessPush)(nil),       // 8: cli.PaymentPurchaseSuccessPush
	(*PaymentCreateOrderPush)(nil),           // 9: cli.PaymentCreateOrderPush
	(*PaymentQueryRecordListRequest)(nil),    // 10: cli.PaymentQueryRecordListRequest
	(*PaymentQueryRecordListResponse)(nil),   // 11: cli.PaymentQueryRecordListResponse
	(*Prop)(nil),                             // 12: cli.Prop
	(*CoinRecord)(nil),                       // 13: cli.CoinRecord
}
var file_payment_proto_depIdxs = []int32{
	12, // 0: cli.PaymentPurchaseSuccessPush.ClaimPropList:type_name -> cli.Prop
	13, // 1: cli.PaymentQueryRecordListResponse.RecordList:type_name -> cli.CoinRecord
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	file_structs_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_payment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentOrderIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentOrderIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentCreateOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentCreateOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentCustomCreateOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentCustomCreateOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentPurchaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentPurchaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentPurchaseSuccessPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentCreateOrderPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentQueryRecordListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payment_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaymentQueryRecordListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_payment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_rawDesc = nil
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
