// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.0
// source: withdraw.proto

package cli

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WithdrawChannelConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`      // 通道类型
	IsOpen bool   `protobuf:"varint,2,opt,name=IsOpen,proto3" json:"IsOpen,omitempty"` // 是否开放
	Weight int64  `protobuf:"varint,3,opt,name=Weight,proto3" json:"Weight,omitempty"` // 通道权重
}

func (x *WithdrawChannelConfig) Reset() {
	*x = WithdrawChannelConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdraw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawChannelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawChannelConfig) ProtoMessage() {}

func (x *WithdrawChannelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawChannelConfig.ProtoReflect.Descriptor instead.
func (*WithdrawChannelConfig) Descriptor() ([]byte, []int) {
	return file_withdraw_proto_rawDescGZIP(), []int{0}
}

func (x *WithdrawChannelConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WithdrawChannelConfig) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *WithdrawChannelConfig) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

// WithdrawConditionConfig 提现限制
type WithdrawConditionConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SwitchCharge bool  `protobuf:"varint,1,opt,name=SwitchCharge,proto3" json:"SwitchCharge,omitempty"` // 提现是否开启充值限制
	SwitchLimit  bool  `protobuf:"varint,2,opt,name=SwitchLimit,proto3" json:"SwitchLimit,omitempty"`   // 提现是否开启充值额度限制
	Limit        int64 `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`               // 提现限制的充值额度(x10000)
}

func (x *WithdrawConditionConfig) Reset() {
	*x = WithdrawConditionConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdraw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawConditionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawConditionConfig) ProtoMessage() {}

func (x *WithdrawConditionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawConditionConfig.ProtoReflect.Descriptor instead.
func (*WithdrawConditionConfig) Descriptor() ([]byte, []int) {
	return file_withdraw_proto_rawDescGZIP(), []int{1}
}

func (x *WithdrawConditionConfig) GetSwitchCharge() bool {
	if x != nil {
		return x.SwitchCharge
	}
	return false
}

func (x *WithdrawConditionConfig) GetSwitchLimit() bool {
	if x != nil {
		return x.SwitchLimit
	}
	return false
}

func (x *WithdrawConditionConfig) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// WithdrawQueryStatusRequest 查询提现状态请求
type WithdrawQueryStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WithdrawQueryStatusRequest) Reset() {
	*x = WithdrawQueryStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdraw_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawQueryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawQueryStatusRequest) ProtoMessage() {}

func (x *WithdrawQueryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawQueryStatusRequest.ProtoReflect.Descriptor instead.
func (*WithdrawQueryStatusRequest) Descriptor() ([]byte, []int) {
	return file_withdraw_proto_rawDescGZIP(), []int{2}
}

type WithdrawQueryStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"ConditionConfig"
	ConditionConfig *WithdrawConditionConfig `protobuf:"bytes,2,opt,name=ConditionConfig,proto3" json:"ConditionConfig,omitempty"`
	// @inject_tag: json:"FreeCoin"
	FreeCoin int64 `protobuf:"varint,3,opt,name=FreeCoin,proto3" json:"FreeCoin,omitempty"` //免费不可提现(x10000)
	// @inject_tag: json:"FreeWinCoin"
	FreeWinCoin int64 `protobuf:"varint,4,opt,name=FreeWinCoin,proto3" json:"FreeWinCoin,omitempty"` //免费可提现(x10000)
	// @inject_tag: json:"RechargeCoin"
	RechargeCoin int64 `protobuf:"varint,5,opt,name=RechargeCoin,proto3" json:"RechargeCoin,omitempty"` //付费不可提现(x10000)
	// @inject_tag: json:"RechargeWinCoin"
	RechargeWinCoin int64 `protobuf:"varint,6,opt,name=RechargeWinCoin,proto3" json:"RechargeWinCoin,omitempty"` //付费可提现(x10000)
	// @inject_tag: json:"InviteLockCoin"
	InviteLockCoin int64 `protobuf:"varint,7,opt,name=InviteLockCoin,proto3" json:"InviteLockCoin,omitempty"` //推广不可提现(x10000)
	// @inject_tag: json:"InviteWithdrawableCoin"
	InviteWithdrawableCoin int64 `protobuf:"varint,8,opt,name=InviteWithdrawableCoin,proto3" json:"InviteWithdrawableCoin,omitempty"` //推广可提现(x10000)
	// @inject_tag: json:"FreeWithdrawLimit"
	FreeWithdrawLimit int64 `protobuf:"varint,9,opt,name=FreeWithdrawLimit,proto3" json:"FreeWithdrawLimit,omitempty"` // 免费金币的提现额度(x10000)
	// @inject_tag: json:"BindList"
	BindList []string `protobuf:"bytes,10,rep,name=BindList,proto3" json:"BindList,omitempty"` // 绑定信息的json字符串列表
	// @inject_tag: json:"AggIncRechargeCoin"
	AggIncRechargeCoin int64 `protobuf:"varint,11,opt,name=AggIncRechargeCoin,proto3" json:"AggIncRechargeCoin,omitempty"` // 累计获得付费金币
	// @inject_tag: json:"RechargeCurrency"
	RechargeCurrency int64 `protobuf:"varint,12,opt,name=RechargeCurrency,proto3" json:"RechargeCurrency,omitempty"` // 累计付费金额(实际付费钱数x10000)
	// @inject_tag: json:"InProgressCount"
	InProgressCount int64 `protobuf:"varint,13,opt,name=InProgressCount,proto3" json:"InProgressCount,omitempty"` // 提现中的订单数
	// @inject_tag: json:"WithdrawChannelConfig"
	ChannelConfig []*WithdrawChannelConfig `protobuf:"bytes,14,rep,name=ChannelConfig,proto3" json:"ChannelConfig,omitempty"` // 提现通道配置
}

func (x *WithdrawQueryStatusResponse) Reset() {
	*x = WithdrawQueryStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdraw_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawQueryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawQueryStatusResponse) ProtoMessage() {}

func (x *WithdrawQueryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawQueryStatusResponse.ProtoReflect.Descriptor instead.
func (*WithdrawQueryStatusResponse) Descriptor() ([]byte, []int) {
	return file_withdraw_proto_rawDescGZIP(), []int{3}
}

func (x *WithdrawQueryStatusResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WithdrawQueryStatusResponse) GetConditionConfig() *WithdrawConditionConfig {
	if x != nil {
		return x.ConditionConfig
	}
	return nil
}

func (x *WithdrawQueryStatusResponse) GetFreeCoin() int64 {
	if x != nil {
		return x.FreeCoin
	}
	return 0
}

func (x *WithdrawQueryStatusResponse) GetFreeWinCoin() int64 {
	if x != nil {
		return x.FreeWinCoin
	}
	return 0
}

func (x *WithdrawQueryStatusResponse) GetRechargeCoin() int64 {
	if x != nil {
		return x.RechargeCoin
	}
	return 0
}

func (x *WithdrawQueryStatusResponse) GetRechargeWinCoin() int64 {
	if x != nil {
		return x.RechargeWinCoin
	}
	return 0
}

func (x *WithdrawQueryStatusResponse) GetInviteLockCoin() int64 {
	if x != nil {
		return x.InviteLockCoin
	}
	return 0
}

func (x *WithdrawQueryStatusResponse) GetInviteWithdrawableCoin() int64 {
	if x != nil {
		return x.InviteWithdrawableCoin
	}
	return 0
}

func (x *WithdrawQueryStatusResponse) GetFreeWithdrawLimit() int64 {
	if x != nil {
		return x.FreeWithdrawLimit
	}
	return 0
}

func (x *WithdrawQueryStatusResponse) GetBindList() []string {
	if x != nil {
		return x.BindList
	}
	return nil
}

func (x *WithdrawQueryStatusResponse) GetAggIncRechargeCoin() int64 {
	if x != nil {
		return x.AggIncRechargeCoin
	}
	return 0
}

func (x *WithdrawQueryStatusResponse) GetRechargeCurrency() int64 {
	if x != nil {
		return x.RechargeCurrency
	}
	return 0
}

func (x *WithdrawQueryStatusResponse) GetInProgressCount() int64 {
	if x != nil {
		return x.InProgressCount
	}
	return 0
}

func (x *WithdrawQueryStatusResponse) GetChannelConfig() []*WithdrawChannelConfig {
	if x != nil {
		return x.ChannelConfig
	}
	return nil
}

// WithdrawBindRequest 绑定提现信息请求
type WithdrawBindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Type"
	Type string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"` // 提现方式 巴西:"Pix"，美国:"cash"
	// @inject_tag: json:"BindInfo"
	BindInfo string `protobuf:"bytes,2,opt,name=BindInfo,proto3" json:"BindInfo,omitempty"` // 绑定信息的json字符串
}

func (x *WithdrawBindRequest) Reset() {
	*x = WithdrawBindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdraw_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawBindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawBindRequest) ProtoMessage() {}

func (x *WithdrawBindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawBindRequest.ProtoReflect.Descriptor instead.
func (*WithdrawBindRequest) Descriptor() ([]byte, []int) {
	return file_withdraw_proto_rawDescGZIP(), []int{4}
}

func (x *WithdrawBindRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WithdrawBindRequest) GetBindInfo() string {
	if x != nil {
		return x.BindInfo
	}
	return ""
}

type WithdrawBindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *WithdrawBindResponse) Reset() {
	*x = WithdrawBindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdraw_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawBindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawBindResponse) ProtoMessage() {}

func (x *WithdrawBindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawBindResponse.ProtoReflect.Descriptor instead.
func (*WithdrawBindResponse) Descriptor() ([]byte, []int) {
	return file_withdraw_proto_rawDescGZIP(), []int{5}
}

func (x *WithdrawBindResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

// WithdrawCreateOrderRequest 提现下单请求
type WithdrawCreateOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"PackageName"
	PackageName string `protobuf:"bytes,1,opt,name=PackageName,proto3" json:"PackageName,omitempty"` // 包名
	// @inject_tag: json:"Channel"
	Channel string `protobuf:"bytes,2,opt,name=Channel,proto3" json:"Channel,omitempty"` // 渠道
	// @inject_tag: json:"Type"
	Type string `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"` // 提现方式(Pix,cash)
	// @inject_tag: json:"Amount"
	Amount int64 `protobuf:"varint,4,opt,name=Amount,proto3" json:"Amount,omitempty"` // 交易金额(x10000)
	// @inject_tag: json:"Source"
	Source string `protobuf:"bytes,5,opt,name=Source,proto3" json:"Source,omitempty"` // 提现环境
	// @inject_tag: json:"OrderID"
	OrderID string `protobuf:"bytes,6,opt,name=OrderID,proto3" json:"OrderID,omitempty"` // 订单ID
	// @inject_tag: json:"BindInfo"
	BindInfo string `protobuf:"bytes,7,opt,name=BindInfo,proto3" json:"BindInfo,omitempty"` // 绑定信息的json字符串
	// @inject_tag: json:"WithdrawType"
	WithdrawType int64 `protobuf:"varint,8,opt,name=WithdrawType,proto3" json:"WithdrawType,omitempty"` // 提现类型(1-免费金币提现2-付费金币提现3-推广金币提现)
}

func (x *WithdrawCreateOrderRequest) Reset() {
	*x = WithdrawCreateOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdraw_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawCreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawCreateOrderRequest) ProtoMessage() {}

func (x *WithdrawCreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawCreateOrderRequest.ProtoReflect.Descriptor instead.
func (*WithdrawCreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_withdraw_proto_rawDescGZIP(), []int{6}
}

func (x *WithdrawCreateOrderRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *WithdrawCreateOrderRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *WithdrawCreateOrderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WithdrawCreateOrderRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WithdrawCreateOrderRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *WithdrawCreateOrderRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *WithdrawCreateOrderRequest) GetBindInfo() string {
	if x != nil {
		return x.BindInfo
	}
	return ""
}

func (x *WithdrawCreateOrderRequest) GetWithdrawType() int64 {
	if x != nil {
		return x.WithdrawType
	}
	return 0
}

type WithdrawCreateOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"FreeCoin"
	FreeCoin int64 `protobuf:"varint,2,opt,name=FreeCoin,proto3" json:"FreeCoin,omitempty"` //免费不可提现(x10000)
	// @inject_tag: json:"FreeWinCoin"
	FreeWinCoin int64 `protobuf:"varint,3,opt,name=FreeWinCoin,proto3" json:"FreeWinCoin,omitempty"` //免费可提现(x10000)
	// @inject_tag: json:"RechargeCoin"
	RechargeCoin int64 `protobuf:"varint,4,opt,name=RechargeCoin,proto3" json:"RechargeCoin,omitempty"` //付费不可提现(x10000)
	// @inject_tag: json:"RechargeWinCoin"
	RechargeWinCoin int64 `protobuf:"varint,5,opt,name=RechargeWinCoin,proto3" json:"RechargeWinCoin,omitempty"` //付费可提现(x10000)
	// @inject_tag: json:"InviteLockCoin"
	InviteLockCoin int64 `protobuf:"varint,6,opt,name=InviteLockCoin,proto3" json:"InviteLockCoin,omitempty"` //推广不可提现(x10000)
	// @inject_tag: json:"InviteWithdrawableCoin"
	InviteWithdrawableCoin int64 `protobuf:"varint,7,opt,name=InviteWithdrawableCoin,proto3" json:"InviteWithdrawableCoin,omitempty"` //推广可提现(x10000)
	// @inject_tag: json:"FreeWithdrawLimit"
	FreeWithdrawLimit int64 `protobuf:"varint,8,opt,name=FreeWithdrawLimit,proto3" json:"FreeWithdrawLimit,omitempty"` // 免费金币的提现额度(x10000)
	// @inject_tag: json:"WithdrawType"
	WithdrawType int64 `protobuf:"varint,9,opt,name=WithdrawType,proto3" json:"WithdrawType,omitempty"` // 提现类型(1-免费金币提现2-付费金币提现3-推广金币提现)
	// @inject_tag: json:"WithdrawCoin"
	WithdrawCoin int64 `protobuf:"varint,10,opt,name=WithdrawCoin,proto3" json:"WithdrawCoin,omitempty"` //提现金币(x10000)
	// @inject_tag: json:"OrderID"
	OrderID string `protobuf:"bytes,11,opt,name=OrderID,proto3" json:"OrderID,omitempty"` // 订单ID
}

func (x *WithdrawCreateOrderResponse) Reset() {
	*x = WithdrawCreateOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdraw_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawCreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawCreateOrderResponse) ProtoMessage() {}

func (x *WithdrawCreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawCreateOrderResponse.ProtoReflect.Descriptor instead.
func (*WithdrawCreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_withdraw_proto_rawDescGZIP(), []int{7}
}

func (x *WithdrawCreateOrderResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WithdrawCreateOrderResponse) GetFreeCoin() int64 {
	if x != nil {
		return x.FreeCoin
	}
	return 0
}

func (x *WithdrawCreateOrderResponse) GetFreeWinCoin() int64 {
	if x != nil {
		return x.FreeWinCoin
	}
	return 0
}

func (x *WithdrawCreateOrderResponse) GetRechargeCoin() int64 {
	if x != nil {
		return x.RechargeCoin
	}
	return 0
}

func (x *WithdrawCreateOrderResponse) GetRechargeWinCoin() int64 {
	if x != nil {
		return x.RechargeWinCoin
	}
	return 0
}

func (x *WithdrawCreateOrderResponse) GetInviteLockCoin() int64 {
	if x != nil {
		return x.InviteLockCoin
	}
	return 0
}

func (x *WithdrawCreateOrderResponse) GetInviteWithdrawableCoin() int64 {
	if x != nil {
		return x.InviteWithdrawableCoin
	}
	return 0
}

func (x *WithdrawCreateOrderResponse) GetFreeWithdrawLimit() int64 {
	if x != nil {
		return x.FreeWithdrawLimit
	}
	return 0
}

func (x *WithdrawCreateOrderResponse) GetWithdrawType() int64 {
	if x != nil {
		return x.WithdrawType
	}
	return 0
}

func (x *WithdrawCreateOrderResponse) GetWithdrawCoin() int64 {
	if x != nil {
		return x.WithdrawCoin
	}
	return 0
}

func (x *WithdrawCreateOrderResponse) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

// WithdrawQueryRecordListRequest 查询提现记录请求
type WithdrawQueryRecordListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WithdrawQueryRecordListRequest) Reset() {
	*x = WithdrawQueryRecordListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdraw_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawQueryRecordListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawQueryRecordListRequest) ProtoMessage() {}

func (x *WithdrawQueryRecordListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawQueryRecordListRequest.ProtoReflect.Descriptor instead.
func (*WithdrawQueryRecordListRequest) Descriptor() ([]byte, []int) {
	return file_withdraw_proto_rawDescGZIP(), []int{8}
}

type WithdrawQueryRecordListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"Code"
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	// @inject_tag: json:"RecordList"
	RecordList []*CoinRecord `protobuf:"bytes,2,rep,name=RecordList,proto3" json:"RecordList,omitempty"`
}

func (x *WithdrawQueryRecordListResponse) Reset() {
	*x = WithdrawQueryRecordListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdraw_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawQueryRecordListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawQueryRecordListResponse) ProtoMessage() {}

func (x *WithdrawQueryRecordListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawQueryRecordListResponse.ProtoReflect.Descriptor instead.
func (*WithdrawQueryRecordListResponse) Descriptor() ([]byte, []int) {
	return file_withdraw_proto_rawDescGZIP(), []int{9}
}

func (x *WithdrawQueryRecordListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WithdrawQueryRecordListResponse) GetRecordList() []*CoinRecord {
	if x != nil {
		return x.RecordList
	}
	return nil
}

// WithdrawRefundPush 提现失败退款通知
type WithdrawRefundPush struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"FreeCoin"
	FreeCoin int64 `protobuf:"varint,1,opt,name=FreeCoin,proto3" json:"FreeCoin,omitempty"` //免费不可提现(x10000)
	// @inject_tag: json:"FreeWinCoin"
	FreeWinCoin int64 `protobuf:"varint,2,opt,name=FreeWinCoin,proto3" json:"FreeWinCoin,omitempty"` //免费可提现(x10000)
	// @inject_tag: json:"RechargeCoin"
	RechargeCoin int64 `protobuf:"varint,3,opt,name=RechargeCoin,proto3" json:"RechargeCoin,omitempty"` //付费不可提现(x10000)
	// @inject_tag: json:"RechargeWinCoin"
	RechargeWinCoin int64 `protobuf:"varint,4,opt,name=RechargeWinCoin,proto3" json:"RechargeWinCoin,omitempty"` //付费可提现(x10000)
	// @inject_tag: json:"InviteLockCoin"
	InviteLockCoin int64 `protobuf:"varint,5,opt,name=InviteLockCoin,proto3" json:"InviteLockCoin,omitempty"` //推广不可提现(x10000)
	// @inject_tag: json:"InviteWithdrawableCoin"
	InviteWithdrawableCoin int64 `protobuf:"varint,6,opt,name=InviteWithdrawableCoin,proto3" json:"InviteWithdrawableCoin,omitempty"` //推广可提现(x10000)
	// @inject_tag: json:"FreeWithdrawLimit"
	FreeWithdrawLimit int64 `protobuf:"varint,7,opt,name=FreeWithdrawLimit,proto3" json:"FreeWithdrawLimit,omitempty"` // 免费金币的提现额度(x10000)
	// @inject_tag: json:"WithdrawType"
	WithdrawType int64 `protobuf:"varint,8,opt,name=WithdrawType,proto3" json:"WithdrawType,omitempty"` // 提现类型(1-免费金币提现2-付费金币提现3-推广金币提现)
	// @inject_tag: json:"WithdrawCoin"
	WithdrawCoin int64 `protobuf:"varint,9,opt,name=WithdrawCoin,proto3" json:"WithdrawCoin,omitempty"` //提现金币(x10000)
	// @inject_tag: json:"OrderID"
	OrderID string `protobuf:"bytes,10,opt,name=OrderID,proto3" json:"OrderID,omitempty"` //提现订单ID
}

func (x *WithdrawRefundPush) Reset() {
	*x = WithdrawRefundPush{}
	if protoimpl.UnsafeEnabled {
		mi := &file_withdraw_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawRefundPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawRefundPush) ProtoMessage() {}

func (x *WithdrawRefundPush) ProtoReflect() protoreflect.Message {
	mi := &file_withdraw_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawRefundPush.ProtoReflect.Descriptor instead.
func (*WithdrawRefundPush) Descriptor() ([]byte, []int) {
	return file_withdraw_proto_rawDescGZIP(), []int{10}
}

func (x *WithdrawRefundPush) GetFreeCoin() int64 {
	if x != nil {
		return x.FreeCoin
	}
	return 0
}

func (x *WithdrawRefundPush) GetFreeWinCoin() int64 {
	if x != nil {
		return x.FreeWinCoin
	}
	return 0
}

func (x *WithdrawRefundPush) GetRechargeCoin() int64 {
	if x != nil {
		return x.RechargeCoin
	}
	return 0
}

func (x *WithdrawRefundPush) GetRechargeWinCoin() int64 {
	if x != nil {
		return x.RechargeWinCoin
	}
	return 0
}

func (x *WithdrawRefundPush) GetInviteLockCoin() int64 {
	if x != nil {
		return x.InviteLockCoin
	}
	return 0
}

func (x *WithdrawRefundPush) GetInviteWithdrawableCoin() int64 {
	if x != nil {
		return x.InviteWithdrawableCoin
	}
	return 0
}

func (x *WithdrawRefundPush) GetFreeWithdrawLimit() int64 {
	if x != nil {
		return x.FreeWithdrawLimit
	}
	return 0
}

func (x *WithdrawRefundPush) GetWithdrawType() int64 {
	if x != nil {
		return x.WithdrawType
	}
	return 0
}

func (x *WithdrawRefundPush) GetWithdrawCoin() int64 {
	if x != nil {
		return x.WithdrawCoin
	}
	return 0
}

func (x *WithdrawRefundPush) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

var File_withdraw_proto protoreflect.FileDescriptor

var file_withdraw_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x63, 0x6c, 0x69, 0x1a, 0x0d, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x15, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x49, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x57, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x57, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x22, 0x75, 0x0a, 0x17, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x22, 0x0a, 0x0c,
	0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xf7, 0x04, 0x0a, 0x1b, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x43, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x0f, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x72, 0x65, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x46, 0x72, 0x65, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x20,
	0x0a, 0x0b, 0x46, 0x72, 0x65, 0x65, 0x57, 0x69, 0x6e, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x46, 0x72, 0x65, 0x65, 0x57, 0x69, 0x6e, 0x43, 0x6f, 0x69, 0x6e,
	0x12, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x43, 0x6f, 0x69, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65,
	0x43, 0x6f, 0x69, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65,
	0x57, 0x69, 0x6e, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x52,
	0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x57, 0x69, 0x6e, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x26,
	0x0a, 0x0e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x69, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4c, 0x6f,
	0x63, 0x6b, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x36, 0x0a, 0x16, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x69, 0x6e,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x16, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x2c,
	0x0a, 0x11, 0x46, 0x72, 0x65, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x46, 0x72, 0x65, 0x65, 0x57,
	0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x42, 0x69, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x42, 0x69, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x41, 0x67, 0x67, 0x49,
	0x6e, 0x63, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x41, 0x67, 0x67, 0x49, 0x6e, 0x63, 0x52, 0x65, 0x63, 0x68,
	0x61, 0x72, 0x67, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x2a, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x68,
	0x61, 0x72, 0x67, 0x65, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x10, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x28, 0x0a, 0x0f, 0x49, 0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x49,
	0x6e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x40,
	0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18,
	0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6c, 0x69, 0x2e, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x22, 0x45, 0x0a, 0x13, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x42, 0x69, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42,
	0x69, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42,
	0x69, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2a, 0x0a, 0x14, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x42, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x22, 0xf6, 0x01, 0x0a, 0x1a, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x42, 0x69, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x42, 0x69, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x54, 0x79, 0x70, 0x65, 0x22, 0xad, 0x03, 0x0a,
	0x1b, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x46, 0x72, 0x65, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x46, 0x72, 0x65, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b,
	0x46, 0x72, 0x65, 0x65, 0x57, 0x69, 0x6e, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x46, 0x72, 0x65, 0x65, 0x57, 0x69, 0x6e, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x22,
	0x0a, 0x0c, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x43, 0x6f,
	0x69, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x57, 0x69,
	0x6e, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x52, 0x65, 0x63,
	0x68, 0x61, 0x72, 0x67, 0x65, 0x57, 0x69, 0x6e, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x0e,
	0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x6b,
	0x43, 0x6f, 0x69, 0x6e, 0x12, 0x36, 0x0a, 0x16, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x16, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68,
	0x64, 0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x2c, 0x0a, 0x11,
	0x46, 0x72, 0x65, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x46, 0x72, 0x65, 0x65, 0x57, 0x69, 0x74,
	0x68, 0x64, 0x72, 0x61, 0x77, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x57, 0x69,
	0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x43, 0x6f,
	0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x22, 0x20, 0x0a, 0x1e,
	0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x66,
	0x0a, 0x1f, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x6c, 0x69, 0x2e,
	0x43, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x0a, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x90, 0x03, 0x0a, 0x12, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x50, 0x75, 0x73, 0x68, 0x12, 0x1a, 0x0a,
	0x08, 0x46, 0x72, 0x65, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x46, 0x72, 0x65, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x72, 0x65,
	0x65, 0x57, 0x69, 0x6e, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b,
	0x46, 0x72, 0x65, 0x65, 0x57, 0x69, 0x6e, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x52,
	0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x12,
	0x28, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x57, 0x69, 0x6e, 0x43, 0x6f,
	0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x52, 0x65, 0x63, 0x68, 0x61, 0x72,
	0x67, 0x65, 0x57, 0x69, 0x6e, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x49, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x4c, 0x6f, 0x63, 0x6b, 0x43, 0x6f, 0x69,
	0x6e, 0x12, 0x36, 0x0a, 0x16, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x16, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61,
	0x77, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x69, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x46, 0x72, 0x65,
	0x65, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x46, 0x72, 0x65, 0x65, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72,
	0x61, 0x77, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x57,
	0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x57,
	0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x43, 0x6f, 0x69, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x62, 0x2f,
	0x63, 0x6c, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_withdraw_proto_rawDescOnce sync.Once
	file_withdraw_proto_rawDescData = file_withdraw_proto_rawDesc
)

func file_withdraw_proto_rawDescGZIP() []byte {
	file_withdraw_proto_rawDescOnce.Do(func() {
		file_withdraw_proto_rawDescData = protoimpl.X.CompressGZIP(file_withdraw_proto_rawDescData)
	})
	return file_withdraw_proto_rawDescData
}

var file_withdraw_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_withdraw_proto_goTypes = []interface{}{
	(*WithdrawChannelConfig)(nil),           // 0: cli.WithdrawChannelConfig
	(*WithdrawConditionConfig)(nil),         // 1: cli.WithdrawConditionConfig
	(*WithdrawQueryStatusRequest)(nil),      // 2: cli.WithdrawQueryStatusRequest
	(*WithdrawQueryStatusResponse)(nil),     // 3: cli.WithdrawQueryStatusResponse
	(*WithdrawBindRequest)(nil),             // 4: cli.WithdrawBindRequest
	(*WithdrawBindResponse)(nil),            // 5: cli.WithdrawBindResponse
	(*WithdrawCreateOrderRequest)(nil),      // 6: cli.WithdrawCreateOrderRequest
	(*WithdrawCreateOrderResponse)(nil),     // 7: cli.WithdrawCreateOrderResponse
	(*WithdrawQueryRecordListRequest)(nil),  // 8: cli.WithdrawQueryRecordListRequest
	(*WithdrawQueryRecordListResponse)(nil), // 9: cli.WithdrawQueryRecordListResponse
	(*WithdrawRefundPush)(nil),              // 10: cli.WithdrawRefundPush
	(*CoinRecord)(nil),                      // 11: cli.CoinRecord
}
var file_withdraw_proto_depIdxs = []int32{
	1,  // 0: cli.WithdrawQueryStatusResponse.ConditionConfig:type_name -> cli.WithdrawConditionConfig
	0,  // 1: cli.WithdrawQueryStatusResponse.ChannelConfig:type_name -> cli.WithdrawChannelConfig
	11, // 2: cli.WithdrawQueryRecordListResponse.RecordList:type_name -> cli.CoinRecord
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_withdraw_proto_init() }
func file_withdraw_proto_init() {
	if File_withdraw_proto != nil {
		return
	}
	file_structs_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_withdraw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawChannelConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdraw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawConditionConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdraw_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawQueryStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdraw_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawQueryStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdraw_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawBindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdraw_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawBindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdraw_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawCreateOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdraw_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawCreateOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdraw_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawQueryRecordListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdraw_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawQueryRecordListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_withdraw_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawRefundPush); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_withdraw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_withdraw_proto_goTypes,
		DependencyIndexes: file_withdraw_proto_depIdxs,
		MessageInfos:      file_withdraw_proto_msgTypes,
	}.Build()
	File_withdraw_proto = out.File
	file_withdraw_proto_rawDesc = nil
	file_withdraw_proto_goTypes = nil
	file_withdraw_proto_depIdxs = nil
}
